linters:
  enable:
    - gofmt
    - golint
    - misspell
    - typecheck
    - errcheck
run:
  skip-dirs:
    - modelplugin

issues:
  exclude-rules:
    - path: pkg/southbound/e2ap/asn1cgo/TriggeringMessage.go
      linters:
        - misspell
    - path: pkg/southbound/e2ap/pdubuilder/ric-subscription-delete-failure_test.go
      linters:
        - misspell
    - path: pkg/southbound/e2ap/asn1cgo/CriticalityDiagnostics_test.go
      linters:
        - misspell
