linters:
  enable:
    - gofmt
    - golint
    - misspell
    - typecheck
    - errcheck
    - dogsled
    - unconvert
    - nakedret
    - scopelint
run:
  skip-dirs:
    - modelplugin

issues:
  exclude-rules:
    - path: pkg/southbound/e2ap/asn1cgo/TriggeringMessage.go
      linters:
        - misspell
    - path: pkg/southbound/e2ap/pdubuilder/ric-subscription-delete-failure_test.go
      linters:
        - misspell
    - path: pkg/southbound/e2ap/asn1cgo/CriticalityDiagnostics_test.go
      linters:
        - misspell
    - path: pkg/southbound/e2ap/pdubuilder/ric-subscription-failure_test.go
      linters:
        - misspell
    - path: pkg/southbound/e2ap/pdudecoder/ricSubscriptionFailureDecoder_test.go
      linters:
        - misspell
    - path: pkg/southbound/e2ap/pdubuilder/e2-setup-failure_test.go
      linters:
        - misspell
    - path: pkg/southbound/e2ap/pdubuilder/error-indication_test.go
      linters:
        - misspell
    - path: pkg/southbound/e2ap101/pdubuilder/ric-subscription-delete-failure_test.go
      linters:
        - misspell
    - path: pkg/southbound/e2ap101/asn1cgo/CriticalityDiagnostics_test.go
      linters:
        - misspell
    - path: pkg/southbound/e2ap101/pdubuilder/ric-subscription-failure_test.go
      linters:
        - misspell
    - path: pkg/southbound/e2ap101/pdudecoder/ricSubscriptionFailureDecoder_test.go
      linters:
        - misspell
    - path: pkg/southbound/e2ap101/pdubuilder/e2-setup-failure_test.go
      linters:
        - misspell
    - path: pkg/southbound/e2ap101/pdubuilder/error-indication_test.go
      linters:
        - misspell
    - path: pkg/southbound/e2ap101/asn1cgo/
      linters:
        - deadcode
        - unused
