/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-IEs"
 * 	found in "../../../../api/e2ap/v1beta2/e2ap-v01.01.00.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER -no-gen-OER -D.`
 */

#ifndef	_RANfunctionRevisionVone_H_
#define	_RANfunctionRevisionVone_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* RANfunctionRevisionVone */
typedef long	 RANfunctionRevisionVone_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_RANfunctionRevisionVone_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_RANfunctionRevisionVone;
asn_struct_free_f RANfunctionRevisionVone_free;
asn_struct_print_f RANfunctionRevisionVone_print;
asn_constr_check_f RANfunctionRevisionVone_constraint;
ber_type_decoder_f RANfunctionRevisionVone_decode_ber;
der_type_encoder_f RANfunctionRevisionVone_encode_der;
xer_type_decoder_f RANfunctionRevisionVone_decode_xer;
xer_type_encoder_f RANfunctionRevisionVone_encode_xer;
per_type_decoder_f RANfunctionRevisionVone_decode_uper;
per_type_encoder_f RANfunctionRevisionVone_encode_uper;
per_type_decoder_f RANfunctionRevisionVone_decode_aper;
per_type_encoder_f RANfunctionRevisionVone_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _RANfunctionRevisionVone_H_ */
#include "asn_internal.h"
