/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-IEs"
 * 	found in "../../../../api/e2ap/v1beta2/e2ap-v01.01.00.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER -no-gen-OER -D.`
 */

#ifndef	_RICindicationSNVone_H_
#define	_RICindicationSNVone_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* RICindicationSNVone */
typedef long	 RICindicationSNVone_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RICindicationSNVone;
asn_struct_free_f RICindicationSNVone_free;
asn_struct_print_f RICindicationSNVone_print;
asn_constr_check_f RICindicationSNVone_constraint;
ber_type_decoder_f RICindicationSNVone_decode_ber;
der_type_encoder_f RICindicationSNVone_encode_der;
xer_type_decoder_f RICindicationSNVone_decode_xer;
xer_type_encoder_f RICindicationSNVone_encode_xer;
per_type_decoder_f RICindicationSNVone_decode_uper;
per_type_encoder_f RICindicationSNVone_encode_uper;
per_type_decoder_f RICindicationSNVone_decode_aper;
per_type_encoder_f RICindicationSNVone_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _RICindicationSNVone_H_ */
#include "asn_internal.h"
