// SPDX-FileCopyrightText: 2020-present Open Networking Foundation <info@opennetworking.org>
//
// SPDX-License-Identifier: Apache-2.0

package choiceOptions //nolint

import (
	v1 "github.com/onosproject/onos-e2t/api/xnap/v1"
	xnapcommondatatypesv1 "github.com/onosproject/onos-e2t/api/xnap/v1/xnap-commondatatypes"
	xnapiesv1 "github.com/onosproject/onos-e2t/api/xnap/v1/xnap-ies"
	xnappducontentsv1 "github.com/onosproject/onos-e2t/api/xnap/v1/xnap-pdu-contents"
	xnappdudescriptionsv1 "github.com/onosproject/onos-e2t/api/xnap/v1/xnap-pdu-descriptions"
	"reflect"
)

var XnapChoicemap = map[string]map[int]reflect.Type{
	"procedure_stage_choice": {
		1: reflect.TypeOf(xnappducontentsv1.ProcedureStageChoice_FirstDlCount{}),
		2: reflect.TypeOf(xnappducontentsv1.ProcedureStageChoice_DlDiscarding{}),
		3: reflect.TypeOf(xnappducontentsv1.ProcedureStageChoice_ChoiceExtension{}),
	},
	"response_type_reconf_complete": {
		1: reflect.TypeOf(xnappducontentsv1.ResponseTypeReconfComplete_ConfigurationSuccessfullyApplied{}),
		2: reflect.TypeOf(xnappducontentsv1.ResponseTypeReconfComplete_ConfigurationRejectedByMNgRannode{}),
		3: reflect.TypeOf(xnappducontentsv1.ResponseTypeReconfComplete_ChoiceExtension{}),
	},
	"configuration_update_initiating_node_choice": {
		1: reflect.TypeOf(xnappducontentsv1.ConfigurationUpdateInitiatingNodeChoice_GNb{}),
		2: reflect.TypeOf(xnappducontentsv1.ConfigurationUpdateInitiatingNodeChoice_NgENb{}),
		3: reflect.TypeOf(xnappducontentsv1.ConfigurationUpdateInitiatingNodeChoice_ChoiceExtension{}),
	},
	"responding_node_type_config_update_ack": {
		1: reflect.TypeOf(xnappducontentsv1.RespondingNodeTypeConfigUpdateAck_NgENb{}),
		2: reflect.TypeOf(xnappducontentsv1.RespondingNodeTypeConfigUpdateAck_GNb{}),
		3: reflect.TypeOf(xnappducontentsv1.RespondingNodeTypeConfigUpdateAck_ChoiceExtension{}),
	},
	"initiating_node_type_resource_coord_request": {
		1: reflect.TypeOf(xnappducontentsv1.InitiatingNodeTypeResourceCoordRequest_NgENb{}),
		2: reflect.TypeOf(xnappducontentsv1.InitiatingNodeTypeResourceCoordRequest_GNb{}),
		3: reflect.TypeOf(xnappducontentsv1.InitiatingNodeTypeResourceCoordRequest_ChoiceExtension{}),
	},
	"responding_node_type_resource_coord_response": {
		1: reflect.TypeOf(xnappducontentsv1.RespondingNodeTypeResourceCoordResponse_NgENb{}),
		2: reflect.TypeOf(xnappducontentsv1.RespondingNodeTypeResourceCoordResponse_GNb{}),
		3: reflect.TypeOf(xnappducontentsv1.RespondingNodeTypeResourceCoordResponse_ChoiceExtension{}),
	},
	"served_cells_to_activate": {
		1: reflect.TypeOf(xnappducontentsv1.ServedCellsToActivate_NrCells{}),
		2: reflect.TypeOf(xnappducontentsv1.ServedCellsToActivate_EUtraCells{}),
		3: reflect.TypeOf(xnappducontentsv1.ServedCellsToActivate_ChoiceExtension{}),
	},
	"activated_served_cells": {
		1: reflect.TypeOf(xnappducontentsv1.ActivatedServedCells_NrCells{}),
		2: reflect.TypeOf(xnappducontentsv1.ActivatedServedCells_EUtraCells{}),
		3: reflect.TypeOf(xnappducontentsv1.ActivatedServedCells_ChoiceExtension{}),
	},
	"area_scope_of_mdt_nr": {
		1: reflect.TypeOf(xnapiesv1.AreaScopeOfMdtNR_CellBased{}),
		2: reflect.TypeOf(xnapiesv1.AreaScopeOfMdtNR_TAbased{}),
		3: reflect.TypeOf(xnapiesv1.AreaScopeOfMdtNR_TAibased{}),
	},
	"area_scope_of_mdt_eutra": {
		1: reflect.TypeOf(xnapiesv1.AreaScopeOfMdtEUtra_CellBased{}),
		2: reflect.TypeOf(xnapiesv1.AreaScopeOfMdtEUtra_TAbased{}),
		3: reflect.TypeOf(xnapiesv1.AreaScopeOfMdtEUtra_TAibased{}),
	},
	"cause": {
		1: reflect.TypeOf(xnapiesv1.Cause_RadioNetwork{}),
		2: reflect.TypeOf(xnapiesv1.Cause_Transport{}),
		3: reflect.TypeOf(xnapiesv1.Cause_Protocol{}),
		4: reflect.TypeOf(xnapiesv1.Cause_Misc{}),
		5: reflect.TypeOf(xnapiesv1.Cause_ChoiceExtension{}),
	},
	"cell_assistance_info_nr": {
		1: reflect.TypeOf(xnapiesv1.CellAssistanceInfoNR_LimitedNrList{}),
		2: reflect.TypeOf(xnapiesv1.CellAssistanceInfoNR_FullList{}),
		3: reflect.TypeOf(xnapiesv1.CellAssistanceInfoNR_ChoiceExtension{}),
	},
	"cell_assistance_info_eutra": {
		1: reflect.TypeOf(xnapiesv1.CellAssistanceInfoEUtra_LimitedEutraList{}),
		2: reflect.TypeOf(xnapiesv1.CellAssistanceInfoEUtra_FullList{}),
		3: reflect.TypeOf(xnapiesv1.CellAssistanceInfoEUtra_ChoiceExtension{}),
	},
	"cell_type_choice": {
		1: reflect.TypeOf(xnapiesv1.CellTypeChoice_NgRanEUtra{}),
		2: reflect.TypeOf(xnapiesv1.CellTypeChoice_NgRanNr{}),
		3: reflect.TypeOf(xnapiesv1.CellTypeChoice_EUtran{}),
		4: reflect.TypeOf(xnapiesv1.CellTypeChoice_ChoiceExtension{}),
	},
	"cptransport_layer_information": {
		1: reflect.TypeOf(xnapiesv1.CptransportLayerInformation_EndpointIpaddress{}),
		2: reflect.TypeOf(xnapiesv1.CptransportLayerInformation_ChoiceExtension{}),
	},
	"qo_sflows_to_be_forwarded_item_ext_ies": {
		1: reflect.TypeOf(xnapiesv1.QoSflowsToBeForwardedItemExtIesExtension_IdUlforwardingProposal{}),
		2: reflect.TypeOf(xnapiesv1.QoSflowsToBeForwardedItemExtIesExtension_IdSourceDlforwardingIpaddress{}),
		3: reflect.TypeOf(xnapiesv1.QoSflowsToBeForwardedItemExtIesExtension_IdSourceNodeDlforwardingIpaddress{}),
	},
	"dlcount_choice": {
		1: reflect.TypeOf(xnapiesv1.DlcountChoice_Count12Bits{}),
		2: reflect.TypeOf(xnapiesv1.DlcountChoice_Count18Bits{}),
		3: reflect.TypeOf(xnapiesv1.DlcountChoice_ChoiceExtension{}),
	},
	"drbbstatus_transfer_choice": {
		1: reflect.TypeOf(xnapiesv1.DrbbstatusTransferChoice_PdcpSn_12Bits{}),
		2: reflect.TypeOf(xnapiesv1.DrbbstatusTransferChoice_PdcpSn_18Bits{}),
		3: reflect.TypeOf(xnapiesv1.DrbbstatusTransferChoice_ChoiceExtension{}),
	},
	"event_type_trigger": {
		1: reflect.TypeOf(xnapiesv1.EventTypeTrigger_OutOfCoverage{}),
		2: reflect.TypeOf(xnapiesv1.EventTypeTrigger_EventL1{}),
		3: reflect.TypeOf(xnapiesv1.EventTypeTrigger_ChoiceExtensions{}),
	},
	"measurement_threshold_l1_logged_mdt": {
		1: reflect.TypeOf(xnapiesv1.MeasurementThresholdL1LoggedMdt_ThresholdRsrp{}),
		2: reflect.TypeOf(xnapiesv1.MeasurementThresholdL1LoggedMdt_ThresholdRsrq{}),
	},
	"gnb_id_choice": {
		1: reflect.TypeOf(xnapiesv1.GnbIDChoice_GnbId{}),
		2: reflect.TypeOf(xnapiesv1.GnbIDChoice_ChoiceExtension{}),
	},
	"enb_id_choice": {
		1: reflect.TypeOf(xnapiesv1.EnbIDChoice_EnbIdMacro{}),
		2: reflect.TypeOf(xnapiesv1.EnbIDChoice_EnbIdShortmacro{}),
		3: reflect.TypeOf(xnapiesv1.EnbIDChoice_EnbIdLongmacro{}),
		4: reflect.TypeOf(xnapiesv1.EnbIDChoice_ChoiceExtension{}),
	},
	"global_ng_rannode_id": {
		1: reflect.TypeOf(xnapiesv1.GlobalNgRAnnodeID_GNb{}),
		2: reflect.TypeOf(xnapiesv1.GlobalNgRAnnodeID_NgENb{}),
		3: reflect.TypeOf(xnapiesv1.GlobalNgRAnnodeID_ChoiceExtension{}),
	},
	"initiating_condition_failure_indication": {
		1: reflect.TypeOf(xnapiesv1.InitiatingConditionFailureIndication_RRcreestab{}),
		2: reflect.TypeOf(xnapiesv1.InitiatingConditionFailureIndication_RRcsetup{}),
		3: reflect.TypeOf(xnapiesv1.InitiatingConditionFailureIndication_ChoiceExtension{}),
	},
	"i_rnti": {
		1: reflect.TypeOf(xnapiesv1.IRNti_IRntiFull{}),
		2: reflect.TypeOf(xnapiesv1.IRNti_IRntiShort{}),
		3: reflect.TypeOf(xnapiesv1.IRNti_ChoiceExtension{}),
	},
	"last_visited_cell_item": {
		1: reflect.TypeOf(xnapiesv1.LastVisitedCellItem_NGRanCell{}),
		2: reflect.TypeOf(xnapiesv1.LastVisitedCellItem_EUtranCell{}),
		3: reflect.TypeOf(xnapiesv1.LastVisitedCellItem_UTranCell{}),
		4: reflect.TypeOf(xnapiesv1.LastVisitedCellItem_GEranCell{}),
		5: reflect.TypeOf(xnapiesv1.LastVisitedCellItem_ChoiceExtension{}),
	},
	"mbsfnsubframe_allocation_e_utra": {
		1: reflect.TypeOf(xnapiesv1.MbsfnsubframeAllocationEUTra_Oneframe{}),
		2: reflect.TypeOf(xnapiesv1.MbsfnsubframeAllocationEUTra_Fourframes{}),
		3: reflect.TypeOf(xnapiesv1.MbsfnsubframeAllocationEUTra_ChoiceExtension{}),
	},
	"mdtmode_nr": {
		1: reflect.TypeOf(xnapiesv1.MdtmodeNR_ImmediateMdt{}),
		2: reflect.TypeOf(xnapiesv1.MdtmodeNR_LoggedMdt{}),
		3: reflect.TypeOf(xnapiesv1.MdtmodeNR_MDtmodeNrExtension{}),
	},
	"mdtmode_eutra": {
		1: reflect.TypeOf(xnapiesv1.MdtmodeEUtra_ImmediateMdt{}),
		2: reflect.TypeOf(xnapiesv1.MdtmodeEUtra_LoggedMdt{}),
		3: reflect.TypeOf(xnapiesv1.MdtmodeEUtra_MDtmodeEutraExtension{}),
	},
	"measurement_threshold_a2": {
		1: reflect.TypeOf(xnapiesv1.MeasurementThresholdA2_ThresholdRsrp{}),
		2: reflect.TypeOf(xnapiesv1.MeasurementThresholdA2_ThresholdRsrq{}),
		3: reflect.TypeOf(xnapiesv1.MeasurementThresholdA2_ThresholdSinr{}),
		4: reflect.TypeOf(xnapiesv1.MeasurementThresholdA2_ChoiceExtension{}),
	},
	"ng_ran_node_resource_coordination_info": {
		1: reflect.TypeOf(xnapiesv1.NgRAnNodeResourceCoordinationInfo_EutraResourceCoordinationInfo{}),
		2: reflect.TypeOf(xnapiesv1.NgRAnNodeResourceCoordinationInfo_NrResourceCoordinationInfo{}),
	},
	"neighbour_information_nr_mode_info": {
		1: reflect.TypeOf(xnapiesv1.NeighbourInformationNRModeInfo_FddInfo{}),
		2: reflect.TypeOf(xnapiesv1.NeighbourInformationNRModeInfo_TddInfo{}),
		3: reflect.TypeOf(xnapiesv1.NeighbourInformationNRModeInfo_ChoiceExtension{}),
	},
	"ng_ran_cell_identity": {
		1: reflect.TypeOf(xnapiesv1.NgRAnCellIdentity_Nr{}),
		2: reflect.TypeOf(xnapiesv1.NgRAnCellIdentity_EUtra{}),
		3: reflect.TypeOf(xnapiesv1.NgRAnCellIdentity_ChoiceExtension{}),
	},
	"ng_ran_cell_pci": {
		1: reflect.TypeOf(xnapiesv1.NgRAnCellPci_Nr{}),
		2: reflect.TypeOf(xnapiesv1.NgRAnCellPci_EUtra{}),
		3: reflect.TypeOf(xnapiesv1.NgRAnCellPci_ChoiceExtension{}),
	},
	"npn_broadcast_information": {
		1: reflect.TypeOf(xnapiesv1.NpnBroadcastInformation_SnpnInformation{}),
		2: reflect.TypeOf(xnapiesv1.NpnBroadcastInformation_PniNpnInformation{}),
		3: reflect.TypeOf(xnapiesv1.NpnBroadcastInformation_ChoiceExtension{}),
	},
	"npnmobility_information": {
		1: reflect.TypeOf(xnapiesv1.NpnmobilityInformation_SnpnMobilityInformation{}),
		2: reflect.TypeOf(xnapiesv1.NpnmobilityInformation_PniNpnMobilityInformation{}),
		3: reflect.TypeOf(xnapiesv1.NpnmobilityInformation_ChoiceExtension{}),
	},
	"npnpaging_assistance_information": {
		1: reflect.TypeOf(xnapiesv1.NpnpagingAssistanceInformation_PniNpnInformation{}),
		2: reflect.TypeOf(xnapiesv1.NpnpagingAssistanceInformation_ChoiceExtension{}),
	},
	"npn_support": {
		1: reflect.TypeOf(xnapiesv1.NpnSupport_SNpn{}),
		2: reflect.TypeOf(xnapiesv1.NpnSupport_ChoiceExtensions{}),
	},
	"fdd_or_tdd_nprachconfiguration": {
		1: reflect.TypeOf(xnapiesv1.FddortddNprachconfiguration_Fdd{}),
		2: reflect.TypeOf(xnapiesv1.FddortddNprachconfiguration_Tdd{}),
		3: reflect.TypeOf(xnapiesv1.FddortddNprachconfiguration_ChoiceExtension{}),
	},
	"nrmode_info": {
		1: reflect.TypeOf(xnapiesv1.NrmodeInfo_Fdd{}),
		2: reflect.TypeOf(xnapiesv1.NrmodeInfo_Tdd{}),
		3: reflect.TypeOf(xnapiesv1.NrmodeInfo_ChoiceExtension{}),
	},
	"pdcpchange_indication": {
		1: reflect.TypeOf(xnapiesv1.PdcpchangeIndication_FromSNgRanNode{}),
		2: reflect.TypeOf(xnapiesv1.PdcpchangeIndication_FromMNgRanNode{}),
		3: reflect.TypeOf(xnapiesv1.PdcpchangeIndication_ChoiceExtension{}),
	},
	"qo_scharacteristics": {
		1: reflect.TypeOf(xnapiesv1.QoScharacteristics_NonDynamic{}),
		2: reflect.TypeOf(xnapiesv1.QoScharacteristics_Dynamic{}),
		3: reflect.TypeOf(xnapiesv1.QoScharacteristics_ChoiceExtension{}),
	},
	"radio_resource_status": {
		1: reflect.TypeOf(xnapiesv1.RadioResourceStatus_NgENbRadioResourceStatus{}),
		2: reflect.TypeOf(xnapiesv1.RadioResourceStatus_GNbRadioResourceStatus{}),
		3: reflect.TypeOf(xnapiesv1.RadioResourceStatus_ChoiceExtension{}),
	},
	"ranpaging_area_choice": {
		1: reflect.TypeOf(xnapiesv1.RanpagingAreaChoice_CellList{}),
		2: reflect.TypeOf(xnapiesv1.RanpagingAreaChoice_RAnareaIdList{}),
		3: reflect.TypeOf(xnapiesv1.RanpagingAreaChoice_ChoiceExtension{}),
	},
	"report_type": {
		1: reflect.TypeOf(xnapiesv1.ReportType_Periodical{}),
		2: reflect.TypeOf(xnapiesv1.ReportType_EventTriggered{}),
	},
	"reset_request_type_info": {
		1: reflect.TypeOf(xnapiesv1.ResetRequestTypeInfo_FullReset{}),
		2: reflect.TypeOf(xnapiesv1.ResetRequestTypeInfo_PartialReset{}),
		3: reflect.TypeOf(xnapiesv1.ResetRequestTypeInfo_ChoiceExtension{}),
	},
	"reset_response_type_info": {
		1: reflect.TypeOf(xnapiesv1.ResetResponseTypeInfo_FullReset{}),
		2: reflect.TypeOf(xnapiesv1.ResetResponseTypeInfo_PartialReset{}),
		3: reflect.TypeOf(xnapiesv1.ResetResponseTypeInfo_ChoiceExtension{}),
	},
	"rrcreestab_initiated_reporting": {
		1: reflect.TypeOf(xnapiesv1.RrcreestabInitiatedReporting_RRcreestabReportingWoUerlfreport{}),
		2: reflect.TypeOf(xnapiesv1.RrcreestabInitiatedReporting_RRcreestabReportingWithUerlfreport{}),
		3: reflect.TypeOf(xnapiesv1.RrcreestabInitiatedReporting_ChoiceExtension{}),
	},
	"rrcsetup_initiated_reporting": {
		1: reflect.TypeOf(xnapiesv1.RrcsetupInitiatedReporting_RRcsetupReportingWithUerlfreport{}),
		2: reflect.TypeOf(xnapiesv1.RrcsetupInitiatedReporting_ChoiceExtension{}),
	},
	"served_cell_information_e_utra_mode_info": {
		1: reflect.TypeOf(xnapiesv1.ServedCellInformationEUTraModeInfo_Fdd{}),
		2: reflect.TypeOf(xnapiesv1.ServedCellInformationEUTraModeInfo_Tdd{}),
		3: reflect.TypeOf(xnapiesv1.ServedCellInformationEUTraModeInfo_ChoiceExtension{}),
	},
	"shared_resource_type": {
		1: reflect.TypeOf(xnapiesv1.SharedResourceType_UlOnlySharing{}),
		2: reflect.TypeOf(xnapiesv1.SharedResourceType_UlAndDlSharing{}),
		3: reflect.TypeOf(xnapiesv1.SharedResourceType_ChoiceExtension{}),
	},
	"shared_resource_type_uldl_sharing": {
		1: reflect.TypeOf(xnapiesv1.SharedResourceTypeULdlSharing_UlResources{}),
		2: reflect.TypeOf(xnapiesv1.SharedResourceTypeULdlSharing_DlResources{}),
		3: reflect.TypeOf(xnapiesv1.SharedResourceTypeULdlSharing_ChoiceExtension{}),
	},
	"shared_resource_type_uldl_sharing_ul_resources": {
		1: reflect.TypeOf(xnapiesv1.SharedResourceTypeULdlSharingULResources_Unchanged{}),
		2: reflect.TypeOf(xnapiesv1.SharedResourceTypeULdlSharingULResources_Changed{}),
		3: reflect.TypeOf(xnapiesv1.SharedResourceTypeULdlSharingULResources_ChoiceExtension{}),
	},
	"shared_resource_type_uldl_sharing_dl_resources": {
		1: reflect.TypeOf(xnapiesv1.SharedResourceTypeULdlSharingDLResources_Unchanged{}),
		2: reflect.TypeOf(xnapiesv1.SharedResourceTypeULdlSharingDLResources_Changed{}),
		3: reflect.TypeOf(xnapiesv1.SharedResourceTypeULdlSharingDLResources_ChoiceExtension{}),
	},
	"ssb_positions_in_burst": {
		1: reflect.TypeOf(xnapiesv1.SsbPositionsInBurst_ShortBitmap{}),
		2: reflect.TypeOf(xnapiesv1.SsbPositionsInBurst_MediumBitmap{}),
		3: reflect.TypeOf(xnapiesv1.SsbPositionsInBurst_LongBitmap{}),
		4: reflect.TypeOf(xnapiesv1.SsbPositionsInBurst_ChoiceExtension{}),
	},
	"symbol_allocation_in_slot": {
		1: reflect.TypeOf(xnapiesv1.SymbolAllocationinSlot_AllDl{}),
		2: reflect.TypeOf(xnapiesv1.SymbolAllocationinSlot_AllUl{}),
		3: reflect.TypeOf(xnapiesv1.SymbolAllocationinSlot_BothDlandUl{}),
		4: reflect.TypeOf(xnapiesv1.SymbolAllocationinSlot_ChoiceExtension{}),
	},
	"target_cgi": {
		1: reflect.TypeOf(xnapiesv1.TargetCGi_Nr{}),
		2: reflect.TypeOf(xnapiesv1.TargetCGi_EUtra{}),
		3: reflect.TypeOf(xnapiesv1.TargetCGi_ChoiceExtension{}),
	},
	"uecontext_id": {
		1: reflect.TypeOf(xnapiesv1.UecontextId_RRcresume{}),
		2: reflect.TypeOf(xnapiesv1.UecontextId_RRrcreestablishment{}),
		3: reflect.TypeOf(xnapiesv1.UecontextId_ChoiceExtension{}),
	},
	"uehistory_information_from_the_ue": {
		1: reflect.TypeOf(xnapiesv1.UehistoryInformationFromTheUe_NR{}),
		2: reflect.TypeOf(xnapiesv1.UehistoryInformationFromTheUe_ChoiceExtension{}),
	},
	"ueidentity_index_value": {
		1: reflect.TypeOf(xnapiesv1.UeidentityIndexValue_IndexLength10{}),
		2: reflect.TypeOf(xnapiesv1.UeidentityIndexValue_ChoiceExtension{}),
	},
	"ueranpaging_identity": {
		1: reflect.TypeOf(xnapiesv1.UeranpagingIdentity_IRntiFull{}),
		2: reflect.TypeOf(xnapiesv1.UeranpagingIdentity_ChoiceExtension{}),
	},
	"uerlfreport_container": {
		1: reflect.TypeOf(xnapiesv1.UerlfreportContainer_NRUerlfreportContainer{}),
		2: reflect.TypeOf(xnapiesv1.UerlfreportContainer_LTeUerlfreportContainer{}),
		3: reflect.TypeOf(xnapiesv1.UerlfreportContainer_ChoiceExtension{}),
	},
	"uptransport_layer_information": {
		1: reflect.TypeOf(xnapiesv1.UptransportLayerInformation_GtpTunnel{}),
		2: reflect.TypeOf(xnapiesv1.UptransportLayerInformation_ChoiceExtension{}),
	},
	"private_ie_id": {
		1: reflect.TypeOf(xnapcommondatatypesv1.PrivateIeID_Local{}),
		2: reflect.TypeOf(xnapcommondatatypesv1.PrivateIeID_Global{}),
	},
	"xn_ap_pdu": {
		1: reflect.TypeOf(xnappdudescriptionsv1.XnApPDu_InitiatingMessage{}),
		2: reflect.TypeOf(xnappdudescriptionsv1.XnApPDu_SuccessfulOutcome{}),
		3: reflect.TypeOf(xnappdudescriptionsv1.XnApPDu_UnsuccessfulOutcome{}),
	},
}

var XnapCanonicalChoicemap = map[string]map[int64]reflect.Type{
	"handover_request_ies": {
		int64(v1.ProtocolIeIDsourceNGRANnodeUEXnAPID):       reflect.TypeOf(xnappducontentsv1.HandoverRequestIEsValue_IdSourceNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDCause):                         reflect.TypeOf(xnappducontentsv1.HandoverRequestIEsValue_IdCause{}),
		int64(v1.ProtocolIeIDtargetCellGlobalID):            reflect.TypeOf(xnappducontentsv1.HandoverRequestIEsValue_IdTargetCellGlobalId{}),
		int64(v1.ProtocolIeIDGUAMI):                         reflect.TypeOf(xnappducontentsv1.HandoverRequestIEsValue_IdGuami{}),
		int64(v1.ProtocolIeIDUEContextInfoHORequest):        reflect.TypeOf(xnappducontentsv1.HandoverRequestIEsValue_IdUecontextInfoHorequest{}),
		int64(v1.ProtocolIeIDTraceActivation):               reflect.TypeOf(xnappducontentsv1.HandoverRequestIEsValue_IdTraceActivation{}),
		int64(v1.ProtocolIeIDMaskedIMEISV):                  reflect.TypeOf(xnappducontentsv1.HandoverRequestIEsValue_IdMaskedImeisv{}),
		int64(v1.ProtocolIeIDUEHistoryInformation):          reflect.TypeOf(xnappducontentsv1.HandoverRequestIEsValue_IdUehistoryInformation{}),
		int64(v1.ProtocolIeIDUEContextRefAtSNHORequest):     reflect.TypeOf(xnappducontentsv1.HandoverRequestIEsValue_IdUecontextRefAtSnHorequest{}),
		int64(v1.ProtocolIeIDCHOinformationReq):             reflect.TypeOf(xnappducontentsv1.HandoverRequestIEsValue_IdChoinformationReq{}),
		int64(v1.ProtocolIeIDNRV2XServicesAuthorized):       reflect.TypeOf(xnappducontentsv1.HandoverRequestIEsValue_IdNrv2XservicesAuthorized{}),
		int64(v1.ProtocolIeIDLTEV2XServicesAuthorized):      reflect.TypeOf(xnappducontentsv1.HandoverRequestIEsValue_IdLtev2XservicesAuthorized{}),
		int64(v1.ProtocolIeIDPC5QoSParameters):              reflect.TypeOf(xnappducontentsv1.HandoverRequestIEsValue_IdPc5QoSparameters{}),
		int64(v1.ProtocolIeIDMobilityInformation):           reflect.TypeOf(xnappducontentsv1.HandoverRequestIEsValue_IdMobilityInformation{}),
		int64(v1.ProtocolIeIDUEHistoryInformationFromTheUE): reflect.TypeOf(xnappducontentsv1.HandoverRequestIEsValue_IdUehistoryInformationFromTheUe{}),
		int64(v1.ProtocolIeIDIABNodeIndication):             reflect.TypeOf(xnappducontentsv1.HandoverRequestIEsValue_IdIabnodeIndication{}),
	},
	"uecontext_info_horequest_ext_ies": {
		int64(v1.ProtocolIeIDFiveGCMobilityRestrictionListContainer): reflect.TypeOf(xnappducontentsv1.UecontextInfoHorequestExtIesExtension_IdFiveGcmobilityRestrictionListContainer{}),
		int64(v1.ProtocolIeIDNRUESidelinkAggregateMaximumBitRate):    reflect.TypeOf(xnappducontentsv1.UecontextInfoHorequestExtIesExtension_IdNruesidelinkAggregateMaximumBitRate{}),
		int64(v1.ProtocolIeIDLTEUESidelinkAggregateMaximumBitRate):   reflect.TypeOf(xnappducontentsv1.UecontextInfoHorequestExtIesExtension_IdLteuesidelinkAggregateMaximumBitRate{}),
		int64(v1.ProtocolIeIDMDTPLMNList):                            reflect.TypeOf(xnappducontentsv1.UecontextInfoHorequestExtIesExtension_IdMdtplmnlist{}),
		int64(v1.ProtocolIeIDUERadioCapabilityID):                    reflect.TypeOf(xnappducontentsv1.UecontextInfoHorequestExtIesExtension_IdUeradioCapabilityId{}),
	},
	"handover_request_acknowledge_ies": {
		int64(v1.ProtocolIeIDsourceNGRANnodeUEXnAPID):               reflect.TypeOf(xnappducontentsv1.HandoverRequestAcknowledgeIEsValue_IdSourceNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDtargetNGRANnodeUEXnAPID):               reflect.TypeOf(xnappducontentsv1.HandoverRequestAcknowledgeIEsValue_IdTargetNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDPDUSessionResourcesAdmittedList):       reflect.TypeOf(xnappducontentsv1.HandoverRequestAcknowledgeIEsValue_IdPdusessionResourcesAdmittedList{}),
		int64(v1.ProtocolIeIDPDUSessionResourcesNotAdmittedList):    reflect.TypeOf(xnappducontentsv1.HandoverRequestAcknowledgeIEsValue_IdPdusessionResourcesNotAdmittedList{}),
		int64(v1.ProtocolIeIDTarget2SourceNGRANnodeTranspContainer): reflect.TypeOf(xnappducontentsv1.HandoverRequestAcknowledgeIEsValue_IdTarget2SourceNgRannodeTranspContainer{}),
		int64(v1.ProtocolIeIDUEContextKeptIndicator):                reflect.TypeOf(xnappducontentsv1.HandoverRequestAcknowledgeIEsValue_IdUecontextKeptIndicator{}),
		int64(v1.ProtocolIeIDCriticalityDiagnostics):                reflect.TypeOf(xnappducontentsv1.HandoverRequestAcknowledgeIEsValue_IdCriticalityDiagnostics{}),
		int64(v1.ProtocolIeIDDRBstransferredtoMN):                   reflect.TypeOf(xnappducontentsv1.HandoverRequestAcknowledgeIEsValue_IdDrbsTransferredToMn{}),
		int64(v1.ProtocolIeIDDAPSResponseInfoList):                  reflect.TypeOf(xnappducontentsv1.HandoverRequestAcknowledgeIEsValue_IdDapsresponseInfoList{}),
		int64(v1.ProtocolIeIDCHOinformationAck):                     reflect.TypeOf(xnappducontentsv1.HandoverRequestAcknowledgeIEsValue_IdChoinformationAck{}),
	},
	"handover_preparation_failure_ies": {
		int64(v1.ProtocolIeIDsourceNGRANnodeUEXnAPID):     reflect.TypeOf(xnappducontentsv1.HandoverPreparationFailureIEsValue_IdSourceNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDCause):                       reflect.TypeOf(xnappducontentsv1.HandoverPreparationFailureIEsValue_IdCause{}),
		int64(v1.ProtocolIeIDCriticalityDiagnostics):      reflect.TypeOf(xnappducontentsv1.HandoverPreparationFailureIEsValue_IdCriticalityDiagnostics{}),
		int64(v1.ProtocolIeIDrequestedTargetCellGlobalID): reflect.TypeOf(xnappducontentsv1.HandoverPreparationFailureIEsValue_IdRequestedTargetCellGlobalId{}),
	},
	"snstatus_transfer_ies": {
		int64(v1.ProtocolIeIDsourceNGRANnodeUEXnAPID):         reflect.TypeOf(xnappducontentsv1.SnstatusTransferIEsValue_IdSourceNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDtargetNGRANnodeUEXnAPID):         reflect.TypeOf(xnappducontentsv1.SnstatusTransferIEsValue_IdTargetNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDDRBsSubjectToStatusTransferList): reflect.TypeOf(xnappducontentsv1.SnstatusTransferIEsValue_IdDrbsSubjectToStatusTransferList{}),
	},
	"uecontext_release_ies": {
		int64(v1.ProtocolIeIDsourceNGRANnodeUEXnAPID): reflect.TypeOf(xnappducontentsv1.UecontextReleaseIEsValue_IdSourceNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDtargetNGRANnodeUEXnAPID): reflect.TypeOf(xnappducontentsv1.UecontextReleaseIEsValue_IdTargetNgRannodeUexnApid{}),
	},
	"handover_cancel_ies": {
		int64(v1.ProtocolIeIDsourceNGRANnodeUEXnAPID): reflect.TypeOf(xnappducontentsv1.HandoverCancelIEsValue_IdSourceNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDtargetNGRANnodeUEXnAPID): reflect.TypeOf(xnappducontentsv1.HandoverCancelIEsValue_IdTargetNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDCause):                   reflect.TypeOf(xnappducontentsv1.HandoverCancelIEsValue_IdCause{}),
		int64(v1.ProtocolIeIDtargetCellsToCancel):     reflect.TypeOf(xnappducontentsv1.HandoverCancelIEsValue_IdTargetCellsToCancel{}),
	},
	"handover_success_ies": {
		int64(v1.ProtocolIeIDsourceNGRANnodeUEXnAPID):     reflect.TypeOf(xnappducontentsv1.HandoverSuccessIEsValue_IdSourceNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDtargetNGRANnodeUEXnAPID):     reflect.TypeOf(xnappducontentsv1.HandoverSuccessIEsValue_IdTargetNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDrequestedTargetCellGlobalID): reflect.TypeOf(xnappducontentsv1.HandoverSuccessIEsValue_IdRequestedTargetCellGlobalId{}),
	},
	"conditional_handover_cancel_ies": {
		int64(v1.ProtocolIeIDsourceNGRANnodeUEXnAPID): reflect.TypeOf(xnappducontentsv1.ConditionalHandoverCancelIEsValue_IdSourceNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDtargetNGRANnodeUEXnAPID): reflect.TypeOf(xnappducontentsv1.ConditionalHandoverCancelIEsValue_IdTargetNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDCause):                   reflect.TypeOf(xnappducontentsv1.ConditionalHandoverCancelIEsValue_IdCause{}),
		int64(v1.ProtocolIeIDtargetCellsToCancel):     reflect.TypeOf(xnappducontentsv1.ConditionalHandoverCancelIEsValue_IdTargetCellsToCancel{}),
	},
	"early_status_transfer_ies": {
		int64(v1.ProtocolIeIDsourceNGRANnodeUEXnAPID): reflect.TypeOf(xnappducontentsv1.EarlyStatusTransferIEsValue_IdSourceNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDtargetNGRANnodeUEXnAPID): reflect.TypeOf(xnappducontentsv1.EarlyStatusTransferIEsValue_IdTargetNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDprocedureStage):          reflect.TypeOf(xnappducontentsv1.EarlyStatusTransferIEsValue_IdProcedureStage{}),
	},
	"ranpaging_ies": {
		int64(v1.ProtocolIeIDUEIdentityIndexValue):         reflect.TypeOf(xnappducontentsv1.RanpagingIEsValue_IdUeidentityIndexValue{}),
		int64(v1.ProtocolIeIDUERANPagingIdentity):          reflect.TypeOf(xnappducontentsv1.RanpagingIEsValue_IdUeranpagingIdentity{}),
		int64(v1.ProtocolIeIDPagingDRX):                    reflect.TypeOf(xnappducontentsv1.RanpagingIEsValue_IdPagingDrx{}),
		int64(v1.ProtocolIeIDRANPagingArea):                reflect.TypeOf(xnappducontentsv1.RanpagingIEsValue_IdRanpagingArea{}),
		int64(v1.ProtocolIeIDPagingPriority):               reflect.TypeOf(xnappducontentsv1.RanpagingIEsValue_IdPagingPriority{}),
		int64(v1.ProtocolIeIDAssistanceDataForRANPaging):   reflect.TypeOf(xnappducontentsv1.RanpagingIEsValue_IdAssistanceDataForRanpaging{}),
		int64(v1.ProtocolIeIDUERadioCapabilityForPaging):   reflect.TypeOf(xnappducontentsv1.RanpagingIEsValue_IdUeradioCapabilityForPaging{}),
		int64(v1.ProtocolIeIDExtendedUEIdentityIndexValue): reflect.TypeOf(xnappducontentsv1.RanpagingIEsValue_IdExtendedUeidentityIndexValue{}),
		int64(v1.ProtocolIeIDPagingeDRXInformation):        reflect.TypeOf(xnappducontentsv1.RanpagingIEsValue_IdPagingeDrxinformation{}),
		int64(v1.ProtocolIeIDUESpecificDRX):                reflect.TypeOf(xnappducontentsv1.RanpagingIEsValue_IdUespecificDrx{}),
	},
	"retrieve_uecontext_request_ies": {
		int64(v1.ProtocolIeIDnewNGRANnodeUEXnAPID): reflect.TypeOf(xnappducontentsv1.RetrieveUecontextRequestIEsValue_IdNewNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDUEContextID):          reflect.TypeOf(xnappducontentsv1.RetrieveUecontextRequestIEsValue_IdUecontextId{}),
		int64(v1.ProtocolIeIDMACI):                 reflect.TypeOf(xnappducontentsv1.RetrieveUecontextRequestIEsValue_IdMacI{}),
		int64(v1.ProtocolIeIDnewNGRANCellIdentity): reflect.TypeOf(xnappducontentsv1.RetrieveUecontextRequestIEsValue_IdNewNgRanCellIdentity{}),
		int64(v1.ProtocolIeIDRRCResumeCause):       reflect.TypeOf(xnappducontentsv1.RetrieveUecontextRequestIEsValue_IdRrcresumeCause{}),
	},
	"retrieve_uecontext_response_ies": {
		int64(v1.ProtocolIeIDnewNGRANnodeUEXnAPID):          reflect.TypeOf(xnappducontentsv1.RetrieveUecontextResponseIEsValue_IdNewNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDoldNGRANnodeUEXnAPID):          reflect.TypeOf(xnappducontentsv1.RetrieveUecontextResponseIEsValue_IdOldNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDGUAMI):                         reflect.TypeOf(xnappducontentsv1.RetrieveUecontextResponseIEsValue_IdGuami{}),
		int64(v1.ProtocolIeIDUEContextInfoRetrUECtxtResp):   reflect.TypeOf(xnappducontentsv1.RetrieveUecontextResponseIEsValue_IdUecontextInfoRetrUectxtResp{}),
		int64(v1.ProtocolIeIDTraceActivation):               reflect.TypeOf(xnappducontentsv1.RetrieveUecontextResponseIEsValue_IdTraceActivation{}),
		int64(v1.ProtocolIeIDMaskedIMEISV):                  reflect.TypeOf(xnappducontentsv1.RetrieveUecontextResponseIEsValue_IdMaskedImeisv{}),
		int64(v1.ProtocolIeIDLocationReportingInformation):  reflect.TypeOf(xnappducontentsv1.RetrieveUecontextResponseIEsValue_IdLocationReportingInformation{}),
		int64(v1.ProtocolIeIDCriticalityDiagnostics):        reflect.TypeOf(xnappducontentsv1.RetrieveUecontextResponseIEsValue_IdCriticalityDiagnostics{}),
		int64(v1.ProtocolIeIDNRV2XServicesAuthorized):       reflect.TypeOf(xnappducontentsv1.RetrieveUecontextResponseIEsValue_IdNrv2XservicesAuthorized{}),
		int64(v1.ProtocolIeIDLTEV2XServicesAuthorized):      reflect.TypeOf(xnappducontentsv1.RetrieveUecontextResponseIEsValue_IdLtev2XservicesAuthorized{}),
		int64(v1.ProtocolIeIDPC5QoSParameters):              reflect.TypeOf(xnappducontentsv1.RetrieveUecontextResponseIEsValue_IdPc5QoSparameters{}),
		int64(v1.ProtocolIeIDUEHistoryInformation):          reflect.TypeOf(xnappducontentsv1.RetrieveUecontextResponseIEsValue_IdUehistoryInformation{}),
		int64(v1.ProtocolIeIDUEHistoryInformationFromTheUE): reflect.TypeOf(xnappducontentsv1.RetrieveUecontextResponseIEsValue_IdUehistoryInformationFromTheUe{}),
		int64(v1.ProtocolIeIDMDTPLMNList):                   reflect.TypeOf(xnappducontentsv1.RetrieveUecontextResponseIEsValue_IdMdtplmnlist{}),
	},
	"retrieve_uecontext_failure_ies": {
		int64(v1.ProtocolIeIDnewNGRANnodeUEXnAPID):             reflect.TypeOf(xnappducontentsv1.RetrieveUecontextFailureIEsValue_IdNewNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDOldtoNewNGRANnodeResumeContainer): reflect.TypeOf(xnappducontentsv1.RetrieveUecontextFailureIEsValue_IdOldtoNewNgRannodeResumeContainer{}),
		int64(v1.ProtocolIeIDCause):                            reflect.TypeOf(xnappducontentsv1.RetrieveUecontextFailureIEsValue_IdCause{}),
		int64(v1.ProtocolIeIDCriticalityDiagnostics):           reflect.TypeOf(xnappducontentsv1.RetrieveUecontextFailureIEsValue_IdCriticalityDiagnostics{}),
	},
	"xn_uaddress_indication_ies": {
		int64(v1.ProtocolIeIDnewNGRANnodeUEXnAPID):            reflect.TypeOf(xnappducontentsv1.XnUaddressIndicationIEsValue_IdNewNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDoldNGRANnodeUEXnAPID):            reflect.TypeOf(xnappducontentsv1.XnUaddressIndicationIEsValue_IdOldNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDXnUAddressInfoperPDUSessionList): reflect.TypeOf(xnappducontentsv1.XnUaddressIndicationIEsValue_IdXnUaddressInfoperPdusessionList{}),
		int64(v1.ProtocolIeIDCHOMRDCIndicator):                reflect.TypeOf(xnappducontentsv1.XnUaddressIndicationIEsValue_IdChoMrdcIndicator{}),
		int64(v1.ProtocolIeIDCHOMRDCEarlyDataForwarding):      reflect.TypeOf(xnappducontentsv1.XnUaddressIndicationIEsValue_IdChoMrdcEarlyDataForwarding{}),
	},
	"snode_addition_request_ies": {
		int64(v1.ProtocolIeIDMNGRANnodeUEXnAPID):               reflect.TypeOf(xnappducontentsv1.SnodeAdditionRequestIEsValue_IdMNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDUESecurityCapabilities):           reflect.TypeOf(xnappducontentsv1.SnodeAdditionRequestIEsValue_IdUesecurityCapabilities{}),
		int64(v1.ProtocolIeIDsngRANnodeSecurityKey):            reflect.TypeOf(xnappducontentsv1.SnodeAdditionRequestIEsValue_IdSNgRannodeSecurityKey{}),
		int64(v1.ProtocolIeIDSNGRANnodeUEAMBR):                 reflect.TypeOf(xnappducontentsv1.SnodeAdditionRequestIEsValue_IdSNgRannodeUeAmbr{}),
		int64(v1.ProtocolIeIDselectedPLMN):                     reflect.TypeOf(xnappducontentsv1.SnodeAdditionRequestIEsValue_IdSelectedPlmn{}),
		int64(v1.ProtocolIeIDMobilityRestrictionList):          reflect.TypeOf(xnappducontentsv1.SnodeAdditionRequestIEsValue_IdMobilityRestrictionList{}),
		int64(v1.ProtocolIeIDindexToRatFrequSelectionPriority): reflect.TypeOf(xnappducontentsv1.SnodeAdditionRequestIEsValue_IdIndexToRatFrequSelectionPriority{}),
		int64(v1.ProtocolIeIDPDUSessionToBeAddedAddReq):        reflect.TypeOf(xnappducontentsv1.SnodeAdditionRequestIEsValue_IdPdusessionToBeAddedAddReq{}),
		int64(v1.ProtocolIeIDMNtoSNContainer):                  reflect.TypeOf(xnappducontentsv1.SnodeAdditionRequestIEsValue_IdMnToSnContainer{}),
		int64(v1.ProtocolIeIDSNGRANnodeUEXnAPID):               reflect.TypeOf(xnappducontentsv1.SnodeAdditionRequestIEsValue_IdSNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDExpectedUEBehaviour):              reflect.TypeOf(xnappducontentsv1.SnodeAdditionRequestIEsValue_IdExpectedUebehaviour{}),
		int64(v1.ProtocolIeIDrequestedSplitSRB):                reflect.TypeOf(xnappducontentsv1.SnodeAdditionRequestIEsValue_IdRequestedSplitSrb{}),
		int64(v1.ProtocolIeIDPCellID):                          reflect.TypeOf(xnappducontentsv1.SnodeAdditionRequestIEsValue_IdPcellId{}),
		int64(v1.ProtocolIeIDDesiredActNotificationLevel):      reflect.TypeOf(xnappducontentsv1.SnodeAdditionRequestIEsValue_IdDesiredActNotificationLevel{}),
		int64(v1.ProtocolIeIDAvailableDRBIDs):                  reflect.TypeOf(xnappducontentsv1.SnodeAdditionRequestIEsValue_IdAvailableDrbids{}),
		int64(v1.ProtocolIeIDSNGRANnodeMaxIPDataRateUL):        reflect.TypeOf(xnappducontentsv1.SnodeAdditionRequestIEsValue_IdSNgRannodeMaxIpdataRateUl{}),
		int64(v1.ProtocolIeIDSNGRANnodeMaxIPDataRateDL):        reflect.TypeOf(xnappducontentsv1.SnodeAdditionRequestIEsValue_IdSNgRannodeMaxIpdataRateDl{}),
		int64(v1.ProtocolIeIDLocationInformationSNReporting):   reflect.TypeOf(xnappducontentsv1.SnodeAdditionRequestIEsValue_IdLocationInformationSnreporting{}),
		int64(v1.ProtocolIeIDMRDCResourceCoordinationInfo):     reflect.TypeOf(xnappducontentsv1.SnodeAdditionRequestIEsValue_IdMrDcResourceCoordinationInfo{}),
		int64(v1.ProtocolIeIDMaskedIMEISV):                     reflect.TypeOf(xnappducontentsv1.SnodeAdditionRequestIEsValue_IdMaskedImeisv{}),
		int64(v1.ProtocolIeIDNEDCTDMPattern):                   reflect.TypeOf(xnappducontentsv1.SnodeAdditionRequestIEsValue_IdNeDcTdmPattern{}),
		int64(v1.ProtocolIeIDSNGRANnodeAdditionTriggerInd):     reflect.TypeOf(xnappducontentsv1.SnodeAdditionRequestIEsValue_IdSNgRannodeAdditionTriggerInd{}),
		int64(v1.ProtocolIeIDTraceActivation):                  reflect.TypeOf(xnappducontentsv1.SnodeAdditionRequestIEsValue_IdTraceActivation{}),
		int64(v1.ProtocolIeIDRequestedFastMCGRecoveryViaSRB3):  reflect.TypeOf(xnappducontentsv1.SnodeAdditionRequestIEsValue_IdRequestedFastMcgrecoveryViaSrb3{}),
		int64(v1.ProtocolIeIDUERadioCapabilityID):              reflect.TypeOf(xnappducontentsv1.SnodeAdditionRequestIEsValue_IdUeradioCapabilityId{}),
		int64(v1.ProtocolIeIDSourceNGRANnodeID):                reflect.TypeOf(xnappducontentsv1.SnodeAdditionRequestIEsValue_IdSourceNgRanNodeId{}),
	},
	"snode_addition_request_acknowledge_ies": {
		int64(v1.ProtocolIeIDMNGRANnodeUEXnAPID):               reflect.TypeOf(xnappducontentsv1.SnodeAdditionRequestAcknowledgeIEsValue_IdMNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDSNGRANnodeUEXnAPID):               reflect.TypeOf(xnappducontentsv1.SnodeAdditionRequestAcknowledgeIEsValue_IdSNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDPDUSessionAdmittedAddedAddReqAck): reflect.TypeOf(xnappducontentsv1.SnodeAdditionRequestAcknowledgeIEsValue_IdPdusessionAdmittedAddedAddReqAck{}),
		int64(v1.ProtocolIeIDPDUSessionNotAdmittedAddReqAck):   reflect.TypeOf(xnappducontentsv1.SnodeAdditionRequestAcknowledgeIEsValue_IdPdusessionNotAdmittedAddReqAck{}),
		int64(v1.ProtocolIeIDSNtoMNContainer):                  reflect.TypeOf(xnappducontentsv1.SnodeAdditionRequestAcknowledgeIEsValue_IdSnToMnContainer{}),
		int64(v1.ProtocolIeIDadmittedSplitSRB):                 reflect.TypeOf(xnappducontentsv1.SnodeAdditionRequestAcknowledgeIEsValue_IdAdmittedSplitSrb{}),
		int64(v1.ProtocolIeIDRRCConfigIndication):              reflect.TypeOf(xnappducontentsv1.SnodeAdditionRequestAcknowledgeIEsValue_IdRrcconfigIndication{}),
		int64(v1.ProtocolIeIDCriticalityDiagnostics):           reflect.TypeOf(xnappducontentsv1.SnodeAdditionRequestAcknowledgeIEsValue_IdCriticalityDiagnostics{}),
		int64(v1.ProtocolIeIDLocationInformationSNReporting):   reflect.TypeOf(xnappducontentsv1.SnodeAdditionRequestAcknowledgeIEsValue_IdLocationInformationSn{}),
		int64(v1.ProtocolIeIDMRDCResourceCoordinationInfo):     reflect.TypeOf(xnappducontentsv1.SnodeAdditionRequestAcknowledgeIEsValue_IdMrDcResourceCoordinationInfo{}),
		int64(v1.ProtocolIeIDAvailableFastMCGRecoveryViaSRB3):  reflect.TypeOf(xnappducontentsv1.SnodeAdditionRequestAcknowledgeIEsValue_IdAvailableFastMcgrecoveryViaSrb3{}),
		int64(v1.ProtocolIeIDDirectForwardingPathAvailability): reflect.TypeOf(xnappducontentsv1.SnodeAdditionRequestAcknowledgeIEsValue_IdDirectForwardingPathAvailability{}),
	},
	"snode_addition_request_reject_ies": {
		int64(v1.ProtocolIeIDMNGRANnodeUEXnAPID):     reflect.TypeOf(xnappducontentsv1.SnodeAdditionRequestRejectIEsValue_IdMNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDSNGRANnodeUEXnAPID):     reflect.TypeOf(xnappducontentsv1.SnodeAdditionRequestRejectIEsValue_IdSNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDCause):                  reflect.TypeOf(xnappducontentsv1.SnodeAdditionRequestRejectIEsValue_IdCause{}),
		int64(v1.ProtocolIeIDCriticalityDiagnostics): reflect.TypeOf(xnappducontentsv1.SnodeAdditionRequestRejectIEsValue_IdCriticalityDiagnostics{}),
	},
	"snode_reconfiguration_complete_ies": {
		int64(v1.ProtocolIeIDMNGRANnodeUEXnAPID):      reflect.TypeOf(xnappducontentsv1.SnodeReconfigurationCompleteIEsValue_IdMNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDSNGRANnodeUEXnAPID):      reflect.TypeOf(xnappducontentsv1.SnodeReconfigurationCompleteIEsValue_IdSNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDResponseInfoReconfCompl): reflect.TypeOf(xnappducontentsv1.SnodeReconfigurationCompleteIEsValue_IdResponseInfoReconfCompl{}),
	},
	"snode_modification_request_ies": {
		int64(v1.ProtocolIeIDMNGRANnodeUEXnAPID):                     reflect.TypeOf(xnappducontentsv1.SnodeModificationRequestIEsValue_IdMNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDSNGRANnodeUEXnAPID):                     reflect.TypeOf(xnappducontentsv1.SnodeModificationRequestIEsValue_IdSNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDCause):                                  reflect.TypeOf(xnappducontentsv1.SnodeModificationRequestIEsValue_IdCause{}),
		int64(v1.ProtocolIeIDPDCPChangeIndication):                   reflect.TypeOf(xnappducontentsv1.SnodeModificationRequestIEsValue_IdPdcpchangeIndication{}),
		int64(v1.ProtocolIeIDselectedPLMN):                           reflect.TypeOf(xnappducontentsv1.SnodeModificationRequestIEsValue_IdSelectedPlmn{}),
		int64(v1.ProtocolIeIDMobilityRestrictionList):                reflect.TypeOf(xnappducontentsv1.SnodeModificationRequestIEsValue_IdMobilityRestrictionList{}),
		int64(v1.ProtocolIeIDSCGConfigurationQuery):                  reflect.TypeOf(xnappducontentsv1.SnodeModificationRequestIEsValue_IdScgconfigurationQuery{}),
		int64(v1.ProtocolIeIDUEContextInfoSNModRequest):              reflect.TypeOf(xnappducontentsv1.SnodeModificationRequestIEsValue_IdUecontextInfoSnmodRequest{}),
		int64(v1.ProtocolIeIDMNtoSNContainer):                        reflect.TypeOf(xnappducontentsv1.SnodeModificationRequestIEsValue_IdMnToSnContainer{}),
		int64(v1.ProtocolIeIDrequestedSplitSRB):                      reflect.TypeOf(xnappducontentsv1.SnodeModificationRequestIEsValue_IdRequestedSplitSrb{}),
		int64(v1.ProtocolIeIDrequestedSplitSRBrelease):               reflect.TypeOf(xnappducontentsv1.SnodeModificationRequestIEsValue_IdRequestedSplitSrbrelease{}),
		int64(v1.ProtocolIeIDDesiredActNotificationLevel):            reflect.TypeOf(xnappducontentsv1.SnodeModificationRequestIEsValue_IdDesiredActNotificationLevel{}),
		int64(v1.ProtocolIeIDAdditionalDRBIDs):                       reflect.TypeOf(xnappducontentsv1.SnodeModificationRequestIEsValue_IdAdditionalDrbids{}),
		int64(v1.ProtocolIeIDSNGRANnodeMaxIPDataRateUL):              reflect.TypeOf(xnappducontentsv1.SnodeModificationRequestIEsValue_IdSNgRannodeMaxIpdataRateUl{}),
		int64(v1.ProtocolIeIDSNGRANnodeMaxIPDataRateDL):              reflect.TypeOf(xnappducontentsv1.SnodeModificationRequestIEsValue_IdSNgRannodeMaxIpdataRateDl{}),
		int64(v1.ProtocolIeIDLocationInformationSNReporting):         reflect.TypeOf(xnappducontentsv1.SnodeModificationRequestIEsValue_IdLocationInformationSnreporting{}),
		int64(v1.ProtocolIeIDMRDCResourceCoordinationInfo):           reflect.TypeOf(xnappducontentsv1.SnodeModificationRequestIEsValue_IdMrDcResourceCoordinationInfo{}),
		int64(v1.ProtocolIeIDPCellID):                                reflect.TypeOf(xnappducontentsv1.SnodeModificationRequestIEsValue_IdPcellId{}),
		int64(v1.ProtocolIeIDNEDCTDMPattern):                         reflect.TypeOf(xnappducontentsv1.SnodeModificationRequestIEsValue_IdNeDcTdmPattern{}),
		int64(v1.ProtocolIeIDRequestedFastMCGRecoveryViaSRB3):        reflect.TypeOf(xnappducontentsv1.SnodeModificationRequestIEsValue_IdRequestedFastMcgrecoveryViaSrb3{}),
		int64(v1.ProtocolIeIDRequestedFastMCGRecoveryViaSRB3Release): reflect.TypeOf(xnappducontentsv1.SnodeModificationRequestIEsValue_IdRequestedFastMcgrecoveryViaSrb3Release{}),
		int64(v1.ProtocolIeIDSNTriggered):                            reflect.TypeOf(xnappducontentsv1.SnodeModificationRequestIEsValue_IdSntriggered{}),
		int64(v1.ProtocolIeIDTargetNodeID):                           reflect.TypeOf(xnappducontentsv1.SnodeModificationRequestIEsValue_IdTargetNodeId{}),
	},
	"pdusessions_to_be_modified_snmod_request_item_ext_ies": {
		int64(v1.ProtocolIeIDSNSSAI):                                reflect.TypeOf(xnappducontentsv1.PdusessionsToBeModifiedSNmodRequestItemExtIesExtension_IdSNssai{}),
		int64(v1.ProtocolIeIDPDUSessionExpectedUEActivityBehaviour): reflect.TypeOf(xnappducontentsv1.PdusessionsToBeModifiedSNmodRequestItemExtIesExtension_IdPdusessionExpectedUeactivityBehaviour{}),
	},
	"snode_modification_request_acknowledge_ies": {
		int64(v1.ProtocolIeIDMNGRANnodeUEXnAPID):                    reflect.TypeOf(xnappducontentsv1.SnodeModificationRequestAcknowledgeIEsValue_IdMNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDSNGRANnodeUEXnAPID):                    reflect.TypeOf(xnappducontentsv1.SnodeModificationRequestAcknowledgeIEsValue_IdSNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDPDUSessionAdmittedSNModResponse):       reflect.TypeOf(xnappducontentsv1.SnodeModificationRequestAcknowledgeIEsValue_IdPdusessionAdmittedSnmodResponse{}),
		int64(v1.ProtocolIeIDPDUSessionNotAdmittedSNModResponse):    reflect.TypeOf(xnappducontentsv1.SnodeModificationRequestAcknowledgeIEsValue_IdPdusessionNotAdmittedSnmodResponse{}),
		int64(v1.ProtocolIeIDSNtoMNContainer):                       reflect.TypeOf(xnappducontentsv1.SnodeModificationRequestAcknowledgeIEsValue_IdSnToMnContainer{}),
		int64(v1.ProtocolIeIDadmittedSplitSRB):                      reflect.TypeOf(xnappducontentsv1.SnodeModificationRequestAcknowledgeIEsValue_IdAdmittedSplitSrb{}),
		int64(v1.ProtocolIeIDadmittedSplitSRBrelease):               reflect.TypeOf(xnappducontentsv1.SnodeModificationRequestAcknowledgeIEsValue_IdAdmittedSplitSrbrelease{}),
		int64(v1.ProtocolIeIDCriticalityDiagnostics):                reflect.TypeOf(xnappducontentsv1.SnodeModificationRequestAcknowledgeIEsValue_IdCriticalityDiagnostics{}),
		int64(v1.ProtocolIeIDLocationInformationSNReporting):        reflect.TypeOf(xnappducontentsv1.SnodeModificationRequestAcknowledgeIEsValue_IdLocationInformationSn{}),
		int64(v1.ProtocolIeIDMRDCResourceCoordinationInfo):          reflect.TypeOf(xnappducontentsv1.SnodeModificationRequestAcknowledgeIEsValue_IdMrDcResourceCoordinationInfo{}),
		int64(v1.ProtocolIeIDPDUSessionDataForwardingSNModResponse): reflect.TypeOf(xnappducontentsv1.SnodeModificationRequestAcknowledgeIEsValue_IdPdusessionDataForwardingSnmodResponse{}),
		int64(v1.ProtocolIeIDRRCConfigIndication):                   reflect.TypeOf(xnappducontentsv1.SnodeModificationRequestAcknowledgeIEsValue_IdRrcconfigIndication{}),
		int64(v1.ProtocolIeIDAvailableFastMCGRecoveryViaSRB3):       reflect.TypeOf(xnappducontentsv1.SnodeModificationRequestAcknowledgeIEsValue_IdAvailableFastMcgrecoveryViaSrb3{}),
		int64(v1.ProtocolIeIDReleaseFastMCGRecoveryViaSRB3):         reflect.TypeOf(xnappducontentsv1.SnodeModificationRequestAcknowledgeIEsValue_IdReleaseFastMcgrecoveryViaSrb3{}),
		int64(v1.ProtocolIeIDDirectForwardingPathAvailability):      reflect.TypeOf(xnappducontentsv1.SnodeModificationRequestAcknowledgeIEsValue_IdDirectForwardingPathAvailability{}),
	},
	"snode_modification_request_reject_ies": {
		int64(v1.ProtocolIeIDMNGRANnodeUEXnAPID):     reflect.TypeOf(xnappducontentsv1.SnodeModificationRequestRejectIEsValue_IdMNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDSNGRANnodeUEXnAPID):     reflect.TypeOf(xnappducontentsv1.SnodeModificationRequestRejectIEsValue_IdSNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDCause):                  reflect.TypeOf(xnappducontentsv1.SnodeModificationRequestRejectIEsValue_IdCause{}),
		int64(v1.ProtocolIeIDCriticalityDiagnostics): reflect.TypeOf(xnappducontentsv1.SnodeModificationRequestRejectIEsValue_IdCriticalityDiagnostics{}),
	},
	"snode_modification_required_ies": {
		int64(v1.ProtocolIeIDMNGRANnodeUEXnAPID):                  reflect.TypeOf(xnappducontentsv1.SnodeModificationRequiredIEsValue_IdMNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDSNGRANnodeUEXnAPID):                  reflect.TypeOf(xnappducontentsv1.SnodeModificationRequiredIEsValue_IdSNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDCause):                               reflect.TypeOf(xnappducontentsv1.SnodeModificationRequiredIEsValue_IdCause{}),
		int64(v1.ProtocolIeIDPDCPChangeIndication):                reflect.TypeOf(xnappducontentsv1.SnodeModificationRequiredIEsValue_IdPdcpchangeIndication{}),
		int64(v1.ProtocolIeIDPDUSessionToBeModifiedSNModRequired): reflect.TypeOf(xnappducontentsv1.SnodeModificationRequiredIEsValue_IdPdusessionToBeModifiedSnmodRequired{}),
		int64(v1.ProtocolIeIDPDUSessionToBeReleasedSNModRequired): reflect.TypeOf(xnappducontentsv1.SnodeModificationRequiredIEsValue_IdPdusessionToBeReleasedSnmodRequired{}),
		int64(v1.ProtocolIeIDSNtoMNContainer):                     reflect.TypeOf(xnappducontentsv1.SnodeModificationRequiredIEsValue_IdSnToMnContainer{}),
		int64(v1.ProtocolIeIDSpareDRBIDs):                         reflect.TypeOf(xnappducontentsv1.SnodeModificationRequiredIEsValue_IdSpareDrbids{}),
		int64(v1.ProtocolIeIDRequiredNumberOfDRBIDs):              reflect.TypeOf(xnappducontentsv1.SnodeModificationRequiredIEsValue_IdRequiredNumberOfDrbids{}),
		int64(v1.ProtocolIeIDLocationInformationSNReporting):      reflect.TypeOf(xnappducontentsv1.SnodeModificationRequiredIEsValue_IdLocationInformationSn{}),
		int64(v1.ProtocolIeIDMRDCResourceCoordinationInfo):        reflect.TypeOf(xnappducontentsv1.SnodeModificationRequiredIEsValue_IdMrDcResourceCoordinationInfo{}),
		int64(v1.ProtocolIeIDRRCConfigIndication):                 reflect.TypeOf(xnappducontentsv1.SnodeModificationRequiredIEsValue_IdRrcconfigIndication{}),
		int64(v1.ProtocolIeIDAvailableFastMCGRecoveryViaSRB3):     reflect.TypeOf(xnappducontentsv1.SnodeModificationRequiredIEsValue_IdAvailableFastMcgrecoveryViaSrb3{}),
		int64(v1.ProtocolIeIDReleaseFastMCGRecoveryViaSRB3):       reflect.TypeOf(xnappducontentsv1.SnodeModificationRequiredIEsValue_IdReleaseFastMcgrecoveryViaSrb3{}),
		int64(v1.ProtocolIeIDSCGIndicator):                        reflect.TypeOf(xnappducontentsv1.SnodeModificationRequiredIEsValue_IdScgindicator{}),
	},
	"snode_modification_confirm_ies": {
		int64(v1.ProtocolIeIDMNGRANnodeUEXnAPID):                reflect.TypeOf(xnappducontentsv1.SnodeModificationConfirmIEsValue_IdMNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDSNGRANnodeUEXnAPID):                reflect.TypeOf(xnappducontentsv1.SnodeModificationConfirmIEsValue_IdSNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDPDUSessionAdmittedModSNModConfirm): reflect.TypeOf(xnappducontentsv1.SnodeModificationConfirmIEsValue_IdPdusessionAdmittedModSnmodConfirm{}),
		int64(v1.ProtocolIeIDPDUSessionReleasedSNModConfirm):    reflect.TypeOf(xnappducontentsv1.SnodeModificationConfirmIEsValue_IdPdusessionReleasedSnmodConfirm{}),
		int64(v1.ProtocolIeIDMNtoSNContainer):                   reflect.TypeOf(xnappducontentsv1.SnodeModificationConfirmIEsValue_IdMnToSnContainer{}),
		int64(v1.ProtocolIeIDAdditionalDRBIDs):                  reflect.TypeOf(xnappducontentsv1.SnodeModificationConfirmIEsValue_IdAdditionalDrbids{}),
		int64(v1.ProtocolIeIDCriticalityDiagnostics):            reflect.TypeOf(xnappducontentsv1.SnodeModificationConfirmIEsValue_IdCriticalityDiagnostics{}),
		int64(v1.ProtocolIeIDMRDCResourceCoordinationInfo):      reflect.TypeOf(xnappducontentsv1.SnodeModificationConfirmIEsValue_IdMrDcResourceCoordinationInfo{}),
	},
	"snode_modification_refuse_ies": {
		int64(v1.ProtocolIeIDMNGRANnodeUEXnAPID):     reflect.TypeOf(xnappducontentsv1.SnodeModificationRefuseIEsValue_IdMNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDSNGRANnodeUEXnAPID):     reflect.TypeOf(xnappducontentsv1.SnodeModificationRefuseIEsValue_IdSNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDCause):                  reflect.TypeOf(xnappducontentsv1.SnodeModificationRefuseIEsValue_IdCause{}),
		int64(v1.ProtocolIeIDMNtoSNContainer):        reflect.TypeOf(xnappducontentsv1.SnodeModificationRefuseIEsValue_IdMnToSnContainer{}),
		int64(v1.ProtocolIeIDCriticalityDiagnostics): reflect.TypeOf(xnappducontentsv1.SnodeModificationRefuseIEsValue_IdCriticalityDiagnostics{}),
	},
	"snode_release_request_ies": {
		int64(v1.ProtocolIeIDMNGRANnodeUEXnAPID):           reflect.TypeOf(xnappducontentsv1.SnodeReleaseRequestIEsValue_IdMNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDSNGRANnodeUEXnAPID):           reflect.TypeOf(xnappducontentsv1.SnodeReleaseRequestIEsValue_IdSNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDCause):                        reflect.TypeOf(xnappducontentsv1.SnodeReleaseRequestIEsValue_IdCause{}),
		int64(v1.ProtocolIeIDPDUSessionToBeReleasedRelReq): reflect.TypeOf(xnappducontentsv1.SnodeReleaseRequestIEsValue_IdPdusessionToBeReleasedRelReq{}),
		int64(v1.ProtocolIeIDUEContextKeptIndicator):       reflect.TypeOf(xnappducontentsv1.SnodeReleaseRequestIEsValue_IdUecontextKeptIndicator{}),
		int64(v1.ProtocolIeIDMNtoSNContainer):              reflect.TypeOf(xnappducontentsv1.SnodeReleaseRequestIEsValue_IdMnToSnContainer{}),
		int64(v1.ProtocolIeIDDRBstransferredtoMN):          reflect.TypeOf(xnappducontentsv1.SnodeReleaseRequestIEsValue_IdDrbsTransferredToMn{}),
	},
	"snode_release_request_acknowledge_ies": {
		int64(v1.ProtocolIeIDMNGRANnodeUEXnAPID):              reflect.TypeOf(xnappducontentsv1.SnodeReleaseRequestAcknowledgeIEsValue_IdMNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDSNGRANnodeUEXnAPID):              reflect.TypeOf(xnappducontentsv1.SnodeReleaseRequestAcknowledgeIEsValue_IdSNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDPDUSessionToBeReleasedRelReqAck): reflect.TypeOf(xnappducontentsv1.SnodeReleaseRequestAcknowledgeIEsValue_IdPdusessionToBeReleasedRelReqAck{}),
		int64(v1.ProtocolIeIDCriticalityDiagnostics):          reflect.TypeOf(xnappducontentsv1.SnodeReleaseRequestAcknowledgeIEsValue_IdCriticalityDiagnostics{}),
	},
	"snode_release_reject_ies": {
		int64(v1.ProtocolIeIDMNGRANnodeUEXnAPID):     reflect.TypeOf(xnappducontentsv1.SnodeReleaseRejectIEsValue_IdMNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDSNGRANnodeUEXnAPID):     reflect.TypeOf(xnappducontentsv1.SnodeReleaseRejectIEsValue_IdSNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDCause):                  reflect.TypeOf(xnappducontentsv1.SnodeReleaseRejectIEsValue_IdCause{}),
		int64(v1.ProtocolIeIDCriticalityDiagnostics): reflect.TypeOf(xnappducontentsv1.SnodeReleaseRejectIEsValue_IdCriticalityDiagnostics{}),
	},
	"snode_release_required_ies": {
		int64(v1.ProtocolIeIDMNGRANnodeUEXnAPID):               reflect.TypeOf(xnappducontentsv1.SnodeReleaseRequiredIEsValue_IdMNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDSNGRANnodeUEXnAPID):               reflect.TypeOf(xnappducontentsv1.SnodeReleaseRequiredIEsValue_IdSNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDPDUSessionToBeReleasedListRelRqd): reflect.TypeOf(xnappducontentsv1.SnodeReleaseRequiredIEsValue_IdPdusessionToBeReleasedListRelRqd{}),
		int64(v1.ProtocolIeIDCause):                            reflect.TypeOf(xnappducontentsv1.SnodeReleaseRequiredIEsValue_IdCause{}),
		int64(v1.ProtocolIeIDSNtoMNContainer):                  reflect.TypeOf(xnappducontentsv1.SnodeReleaseRequiredIEsValue_IdSnToMnContainer{}),
	},
	"snode_release_confirm_ies": {
		int64(v1.ProtocolIeIDMNGRANnodeUEXnAPID):            reflect.TypeOf(xnappducontentsv1.SnodeReleaseConfirmIEsValue_IdMNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDSNGRANnodeUEXnAPID):            reflect.TypeOf(xnappducontentsv1.SnodeReleaseConfirmIEsValue_IdSNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDPDUSessionReleasedListRelConf): reflect.TypeOf(xnappducontentsv1.SnodeReleaseConfirmIEsValue_IdPdusessionReleasedListRelConf{}),
		int64(v1.ProtocolIeIDCriticalityDiagnostics):        reflect.TypeOf(xnappducontentsv1.SnodeReleaseConfirmIEsValue_IdCriticalityDiagnostics{}),
	},
	"snode_counter_check_request_ies": {
		int64(v1.ProtocolIeIDMNGRANnodeUEXnAPID):           reflect.TypeOf(xnappducontentsv1.SnodeCounterCheckRequestIEsValue_IdMNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDSNGRANnodeUEXnAPID):           reflect.TypeOf(xnappducontentsv1.SnodeCounterCheckRequestIEsValue_IdSNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDBearersSubjectToCounterCheck): reflect.TypeOf(xnappducontentsv1.SnodeCounterCheckRequestIEsValue_IdBearersSubjectToCounterCheck{}),
	},
	"snode_change_required_ies": {
		int64(v1.ProtocolIeIDMNGRANnodeUEXnAPID):             reflect.TypeOf(xnappducontentsv1.SnodeChangeRequiredIEsValue_IdMNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDSNGRANnodeUEXnAPID):             reflect.TypeOf(xnappducontentsv1.SnodeChangeRequiredIEsValue_IdSNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDtargetSNGRANnodeID):             reflect.TypeOf(xnappducontentsv1.SnodeChangeRequiredIEsValue_IdTargetSNgRannodeId{}),
		int64(v1.ProtocolIeIDCause):                          reflect.TypeOf(xnappducontentsv1.SnodeChangeRequiredIEsValue_IdCause{}),
		int64(v1.ProtocolIeIDPDUSessionSNChangeRequiredList): reflect.TypeOf(xnappducontentsv1.SnodeChangeRequiredIEsValue_IdPdusessionSnchangeRequiredList{}),
		int64(v1.ProtocolIeIDSNtoMNContainer):                reflect.TypeOf(xnappducontentsv1.SnodeChangeRequiredIEsValue_IdSnToMnContainer{}),
	},
	"snode_change_confirm_ies": {
		int64(v1.ProtocolIeIDMNGRANnodeUEXnAPID):            reflect.TypeOf(xnappducontentsv1.SnodeChangeConfirmIEsValue_IdMNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDSNGRANnodeUEXnAPID):            reflect.TypeOf(xnappducontentsv1.SnodeChangeConfirmIEsValue_IdSNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDPDUSessionSNChangeConfirmList): reflect.TypeOf(xnappducontentsv1.SnodeChangeConfirmIEsValue_IdPdusessionSnchangeConfirmList{}),
		int64(v1.ProtocolIeIDCriticalityDiagnostics):        reflect.TypeOf(xnappducontentsv1.SnodeChangeConfirmIEsValue_IdCriticalityDiagnostics{}),
	},
	"snode_change_refuse_ies": {
		int64(v1.ProtocolIeIDMNGRANnodeUEXnAPID):     reflect.TypeOf(xnappducontentsv1.SnodeChangeRefuseIEsValue_IdMNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDSNGRANnodeUEXnAPID):     reflect.TypeOf(xnappducontentsv1.SnodeChangeRefuseIEsValue_IdSNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDCause):                  reflect.TypeOf(xnappducontentsv1.SnodeChangeRefuseIEsValue_IdCause{}),
		int64(v1.ProtocolIeIDCriticalityDiagnostics): reflect.TypeOf(xnappducontentsv1.SnodeChangeRefuseIEsValue_IdCriticalityDiagnostics{}),
	},
	"rrctransfer_ies": {
		int64(v1.ProtocolIeIDMNGRANnodeUEXnAPID):               reflect.TypeOf(xnappducontentsv1.RrctransferIEsValue_IdMNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDSNGRANnodeUEXnAPID):               reflect.TypeOf(xnappducontentsv1.RrctransferIEsValue_IdSNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDSplitSRBRRCTransfer):              reflect.TypeOf(xnappducontentsv1.RrctransferIEsValue_IdSplitSrbRrctransfer{}),
		int64(v1.ProtocolIeIDUEReportRRCTransfer):              reflect.TypeOf(xnappducontentsv1.RrctransferIEsValue_IdUereportRrctransfer{}),
		int64(v1.ProtocolIeIDFastMCGRecoveryRRCTransferSNtoMN): reflect.TypeOf(xnappducontentsv1.RrctransferIEsValue_IdFastMcgrecoveryRrctransferSnToMn{}),
		int64(v1.ProtocolIeIDFastMCGRecoveryRRCTransferMNtoSN): reflect.TypeOf(xnappducontentsv1.RrctransferIEsValue_IdFastMcgrecoveryRrctransferMnToSn{}),
	},
	"notification_control_indication_ies": {
		int64(v1.ProtocolIeIDMNGRANnodeUEXnAPID):            reflect.TypeOf(xnappducontentsv1.NotificationControlIndicationIEsValue_IdMNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDSNGRANnodeUEXnAPID):            reflect.TypeOf(xnappducontentsv1.NotificationControlIndicationIEsValue_IdSNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDPDUSessionResourcesNotifyList): reflect.TypeOf(xnappducontentsv1.NotificationControlIndicationIEsValue_IdPdusessionResourcesNotifyList{}),
	},
	"activity_notification_ies": {
		int64(v1.ProtocolIeIDMNGRANnodeUEXnAPID):                    reflect.TypeOf(xnappducontentsv1.ActivityNotificationIEsValue_IdMNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDSNGRANnodeUEXnAPID):                    reflect.TypeOf(xnappducontentsv1.ActivityNotificationIEsValue_IdSNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDUserPlaneTrafficActivityReport):        reflect.TypeOf(xnappducontentsv1.ActivityNotificationIEsValue_IdUserPlaneTrafficActivityReport{}),
		int64(v1.ProtocolIeIDPDUSessionResourcesActivityNotifyList): reflect.TypeOf(xnappducontentsv1.ActivityNotificationIEsValue_IdPdusessionResourcesActivityNotifyList{}),
		int64(v1.ProtocolIeIDRANPagingFailure):                      reflect.TypeOf(xnappducontentsv1.ActivityNotificationIEsValue_IdRanpagingFailure{}),
	},
	"xn_setup_request_ies": {
		int64(v1.ProtocolIeIDGlobalNGRANnodeID):                  reflect.TypeOf(xnappducontentsv1.XnSetupRequestIEsValue_IdGlobalNgRanNodeId{}),
		int64(v1.ProtocolIeIDTAISupportlist):                     reflect.TypeOf(xnappducontentsv1.XnSetupRequestIEsValue_IdTaisupportList{}),
		int64(v1.ProtocolIeIDAMFRegionInformation):               reflect.TypeOf(xnappducontentsv1.XnSetupRequestIEsValue_IdAmfRegionInformation{}),
		int64(v1.ProtocolIeIDListofservedcellsNR):                reflect.TypeOf(xnappducontentsv1.XnSetupRequestIEsValue_IdListOfServedCellsNr{}),
		int64(v1.ProtocolIeIDListofservedcellsEUTRA):             reflect.TypeOf(xnappducontentsv1.XnSetupRequestIEsValue_IdListOfServedCellsEUtra{}),
		int64(v1.ProtocolIeIDInterfaceInstanceIndication):        reflect.TypeOf(xnappducontentsv1.XnSetupRequestIEsValue_IdInterfaceInstanceIndication{}),
		int64(v1.ProtocolIeIDTNLConfigurationInfo):               reflect.TypeOf(xnappducontentsv1.XnSetupRequestIEsValue_IdTnlconfigurationInfo{}),
		int64(v1.ProtocolIeIDPartialListIndicatorNR):             reflect.TypeOf(xnappducontentsv1.XnSetupRequestIEsValue_IdPartialListIndicatorNr{}),
		int64(v1.ProtocolIeIDCellAndCapacityAssistanceInfoNR):    reflect.TypeOf(xnappducontentsv1.XnSetupRequestIEsValue_IdCellAndCapacityAssistanceInfoNr{}),
		int64(v1.ProtocolIeIDPartialListIndicatorEUTRA):          reflect.TypeOf(xnappducontentsv1.XnSetupRequestIEsValue_IdPartialListIndicatorEutra{}),
		int64(v1.ProtocolIeIDCellAndCapacityAssistanceInfoEUTRA): reflect.TypeOf(xnappducontentsv1.XnSetupRequestIEsValue_IdCellAndCapacityAssistanceInfoEutra{}),
	},
	"xn_setup_response_ies": {
		int64(v1.ProtocolIeIDGlobalNGRANnodeID):                  reflect.TypeOf(xnappducontentsv1.XnSetupResponseIEsValue_IdGlobalNgRanNodeId{}),
		int64(v1.ProtocolIeIDTAISupportlist):                     reflect.TypeOf(xnappducontentsv1.XnSetupResponseIEsValue_IdTaisupportList{}),
		int64(v1.ProtocolIeIDListofservedcellsNR):                reflect.TypeOf(xnappducontentsv1.XnSetupResponseIEsValue_IdListOfServedCellsNr{}),
		int64(v1.ProtocolIeIDListofservedcellsEUTRA):             reflect.TypeOf(xnappducontentsv1.XnSetupResponseIEsValue_IdListOfServedCellsEUtra{}),
		int64(v1.ProtocolIeIDCriticalityDiagnostics):             reflect.TypeOf(xnappducontentsv1.XnSetupResponseIEsValue_IdCriticalityDiagnostics{}),
		int64(v1.ProtocolIeIDAMFRegionInformation):               reflect.TypeOf(xnappducontentsv1.XnSetupResponseIEsValue_IdAmfRegionInformation{}),
		int64(v1.ProtocolIeIDInterfaceInstanceIndication):        reflect.TypeOf(xnappducontentsv1.XnSetupResponseIEsValue_IdInterfaceInstanceIndication{}),
		int64(v1.ProtocolIeIDTNLConfigurationInfo):               reflect.TypeOf(xnappducontentsv1.XnSetupResponseIEsValue_IdTnlconfigurationInfo{}),
		int64(v1.ProtocolIeIDPartialListIndicatorNR):             reflect.TypeOf(xnappducontentsv1.XnSetupResponseIEsValue_IdPartialListIndicatorNr{}),
		int64(v1.ProtocolIeIDCellAndCapacityAssistanceInfoNR):    reflect.TypeOf(xnappducontentsv1.XnSetupResponseIEsValue_IdCellAndCapacityAssistanceInfoNr{}),
		int64(v1.ProtocolIeIDPartialListIndicatorEUTRA):          reflect.TypeOf(xnappducontentsv1.XnSetupResponseIEsValue_IdPartialListIndicatorEutra{}),
		int64(v1.ProtocolIeIDCellAndCapacityAssistanceInfoEUTRA): reflect.TypeOf(xnappducontentsv1.XnSetupResponseIEsValue_IdCellAndCapacityAssistanceInfoEutra{}),
	},
	"xn_setup_failure_ies": {
		int64(v1.ProtocolIeIDCause):                       reflect.TypeOf(xnappducontentsv1.XnSetupFailureIEsValue_IdCause{}),
		int64(v1.ProtocolIeIDTimeToWait):                  reflect.TypeOf(xnappducontentsv1.XnSetupFailureIEsValue_IdTimeToWait{}),
		int64(v1.ProtocolIeIDCriticalityDiagnostics):      reflect.TypeOf(xnappducontentsv1.XnSetupFailureIEsValue_IdCriticalityDiagnostics{}),
		int64(v1.ProtocolIeIDInterfaceInstanceIndication): reflect.TypeOf(xnappducontentsv1.XnSetupFailureIEsValue_IdInterfaceInstanceIndication{}),
		int64(v1.ProtocolIeIDMessageOversizeNotification): reflect.TypeOf(xnappducontentsv1.XnSetupFailureIEsValue_IdMessageOversizeNotification{}),
	},
	"ngrannode_configuration_update_ies": {
		int64(v1.ProtocolIeIDTAISupportlist):                          reflect.TypeOf(xnappducontentsv1.NgrannodeConfigurationUpdateIEsValue_IdTaisupportList{}),
		int64(v1.ProtocolIeIDConfigurationUpdateInitiatingNodeChoice): reflect.TypeOf(xnappducontentsv1.NgrannodeConfigurationUpdateIEsValue_IdConfigurationUpdateInitiatingNodeChoice{}),
		int64(v1.ProtocolIeIDTNLAToAddList):                           reflect.TypeOf(xnappducontentsv1.NgrannodeConfigurationUpdateIEsValue_IdTnlaToAddList{}),
		int64(v1.ProtocolIeIDTNLAToRemoveList):                        reflect.TypeOf(xnappducontentsv1.NgrannodeConfigurationUpdateIEsValue_IdTnlaToRemoveList{}),
		int64(v1.ProtocolIeIDTNLAToUpdateList):                        reflect.TypeOf(xnappducontentsv1.NgrannodeConfigurationUpdateIEsValue_IdTnlaToUpdateList{}),
		int64(v1.ProtocolIeIDGlobalNGRANnodeID):                       reflect.TypeOf(xnappducontentsv1.NgrannodeConfigurationUpdateIEsValue_IdGlobalNgRanNodeId{}),
		int64(v1.ProtocolIeIDAMFRegionInformationToAdd):               reflect.TypeOf(xnappducontentsv1.NgrannodeConfigurationUpdateIEsValue_IdAmfRegionInformationToAdd{}),
		int64(v1.ProtocolIeIDAMFRegionInformationToDelete):            reflect.TypeOf(xnappducontentsv1.NgrannodeConfigurationUpdateIEsValue_IdAmfRegionInformationToDelete{}),
		int64(v1.ProtocolIeIDInterfaceInstanceIndication):             reflect.TypeOf(xnappducontentsv1.NgrannodeConfigurationUpdateIEsValue_IdInterfaceInstanceIndication{}),
		int64(v1.ProtocolIeIDTNLConfigurationInfo):                    reflect.TypeOf(xnappducontentsv1.NgrannodeConfigurationUpdateIEsValue_IdTnlconfigurationInfo{}),
	},
	"configuration_update_g_nb": {
		int64(v1.ProtocolIeIDservedCellsToUpdateNR):   reflect.TypeOf(xnappducontentsv1.ConfigurationUpdategNbValue_IdServedCellsToUpdateNr{}),
		int64(v1.ProtocolIeIDcellAssistanceInfoNR):    reflect.TypeOf(xnappducontentsv1.ConfigurationUpdategNbValue_IdCellAssistanceInfoNr{}),
		int64(v1.ProtocolIeIDcellAssistanceInfoEUTRA): reflect.TypeOf(xnappducontentsv1.ConfigurationUpdategNbValue_IdCellAssistanceInfoEutra{}),
	},
	"configuration_update_ng_e_nb": {
		int64(v1.ProtocolIeIDservedCellsToUpdateEUTRA): reflect.TypeOf(xnappducontentsv1.ConfigurationUpdatengeNbValue_IdServedCellsToUpdateEUtra{}),
		int64(v1.ProtocolIeIDcellAssistanceInfoNR):     reflect.TypeOf(xnappducontentsv1.ConfigurationUpdatengeNbValue_IdCellAssistanceInfoNr{}),
		int64(v1.ProtocolIeIDcellAssistanceInfoEUTRA):  reflect.TypeOf(xnappducontentsv1.ConfigurationUpdatengeNbValue_IdCellAssistanceInfoEutra{}),
	},
	"ngrannode_configuration_update_acknowledge_ies": {
		int64(v1.ProtocolIeIDRespondingNodeTypeConfigUpdateAck): reflect.TypeOf(xnappducontentsv1.NgrannodeConfigurationUpdateAcknowledgeIEsValue_IdRespondingNodeTypeConfigUpdateAck{}),
		int64(v1.ProtocolIeIDTNLASetupList):                     reflect.TypeOf(xnappducontentsv1.NgrannodeConfigurationUpdateAcknowledgeIEsValue_IdTnlaSetupList{}),
		int64(v1.ProtocolIeIDTNLAFailedToSetupList):             reflect.TypeOf(xnappducontentsv1.NgrannodeConfigurationUpdateAcknowledgeIEsValue_IdTnlaFailedToSetupList{}),
		int64(v1.ProtocolIeIDCriticalityDiagnostics):            reflect.TypeOf(xnappducontentsv1.NgrannodeConfigurationUpdateAcknowledgeIEsValue_IdCriticalityDiagnostics{}),
		int64(v1.ProtocolIeIDInterfaceInstanceIndication):       reflect.TypeOf(xnappducontentsv1.NgrannodeConfigurationUpdateAcknowledgeIEsValue_IdInterfaceInstanceIndication{}),
		int64(v1.ProtocolIeIDTNLConfigurationInfo):              reflect.TypeOf(xnappducontentsv1.NgrannodeConfigurationUpdateAcknowledgeIEsValue_IdTnlconfigurationInfo{}),
	},
	"responding_node_type_config_update_ack_ng_e_nb_ext_ies": {
		int64(v1.ProtocolIeIDListofservedcellsEUTRA):             reflect.TypeOf(xnappducontentsv1.RespondingNodeTypeConfigUpdateAckngeNbExtIesExtension_IdListOfServedCellsEUtra{}),
		int64(v1.ProtocolIeIDPartialListIndicatorEUTRA):          reflect.TypeOf(xnappducontentsv1.RespondingNodeTypeConfigUpdateAckngeNbExtIesExtension_IdPartialListIndicatorEutra{}),
		int64(v1.ProtocolIeIDCellAndCapacityAssistanceInfoEUTRA): reflect.TypeOf(xnappducontentsv1.RespondingNodeTypeConfigUpdateAckngeNbExtIesExtension_IdCellAndCapacityAssistanceInfoEutra{}),
	},
	"responding_node_type_config_update_ack_g_nb_ext_ies": {
		int64(v1.ProtocolIeIDPartialListIndicatorNR):          reflect.TypeOf(xnappducontentsv1.RespondingNodeTypeConfigUpdateAckgNbExtIesExtension_IdPartialListIndicatorNr{}),
		int64(v1.ProtocolIeIDCellAndCapacityAssistanceInfoNR): reflect.TypeOf(xnappducontentsv1.RespondingNodeTypeConfigUpdateAckgNbExtIesExtension_IdCellAndCapacityAssistanceInfoNr{}),
	},
	"ngrannode_configuration_update_failure_ies": {
		int64(v1.ProtocolIeIDCause):                       reflect.TypeOf(xnappducontentsv1.NgrannodeConfigurationUpdateFailureIEsValue_IdCause{}),
		int64(v1.ProtocolIeIDTimeToWait):                  reflect.TypeOf(xnappducontentsv1.NgrannodeConfigurationUpdateFailureIEsValue_IdTimeToWait{}),
		int64(v1.ProtocolIeIDCriticalityDiagnostics):      reflect.TypeOf(xnappducontentsv1.NgrannodeConfigurationUpdateFailureIEsValue_IdCriticalityDiagnostics{}),
		int64(v1.ProtocolIeIDInterfaceInstanceIndication): reflect.TypeOf(xnappducontentsv1.NgrannodeConfigurationUpdateFailureIEsValue_IdInterfaceInstanceIndication{}),
	},
	"e_utra_nr_cell_resource_coordination_request_ies": {
		int64(v1.ProtocolIeIDinitiatingNodeTypeResourceCoordRequest): reflect.TypeOf(xnappducontentsv1.EUTraNRCellResourceCoordinationRequestIEsValue_IdInitiatingNodeTypeResourceCoordRequest{}),
		int64(v1.ProtocolIeIDInterfaceInstanceIndication):            reflect.TypeOf(xnappducontentsv1.EUTraNRCellResourceCoordinationRequestIEsValue_IdInterfaceInstanceIndication{}),
	},
	"e_utra_nr_cell_resource_coordination_response_ies": {
		int64(v1.ProtocolIeIDrespondingNodeTypeResourceCoordResponse): reflect.TypeOf(xnappducontentsv1.EUTraNRCellResourceCoordinationResponseIEsValue_IdRespondingNodeTypeResourceCoordResponse{}),
		int64(v1.ProtocolIeIDInterfaceInstanceIndication):             reflect.TypeOf(xnappducontentsv1.EUTraNRCellResourceCoordinationResponseIEsValue_IdInterfaceInstanceIndication{}),
	},
	"secondary_ratdata_usage_report_ies": {
		int64(v1.ProtocolIeIDMNGRANnodeUEXnAPID):                      reflect.TypeOf(xnappducontentsv1.SecondaryRatdataUsageReportIEsValue_IdMNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDSNGRANnodeUEXnAPID):                      reflect.TypeOf(xnappducontentsv1.SecondaryRatdataUsageReportIEsValue_IdSNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDPDUSessionResourceSecondaryRATUsageList): reflect.TypeOf(xnappducontentsv1.SecondaryRatdataUsageReportIEsValue_IdPdusessionResourceSecondaryRatusageList{}),
	},
	"xn_removal_request_ies": {
		int64(v1.ProtocolIeIDGlobalNGRANnodeID):           reflect.TypeOf(xnappducontentsv1.XnRemovalRequestIEsValue_IdGlobalNgRanNodeId{}),
		int64(v1.ProtocolIeIDXnRemovalThreshold):          reflect.TypeOf(xnappducontentsv1.XnRemovalRequestIEsValue_IdXnRemovalThreshold{}),
		int64(v1.ProtocolIeIDInterfaceInstanceIndication): reflect.TypeOf(xnappducontentsv1.XnRemovalRequestIEsValue_IdInterfaceInstanceIndication{}),
	},
	"xn_removal_response_ies": {
		int64(v1.ProtocolIeIDGlobalNGRANnodeID):           reflect.TypeOf(xnappducontentsv1.XnRemovalResponseIEsValue_IdGlobalNgRanNodeId{}),
		int64(v1.ProtocolIeIDCriticalityDiagnostics):      reflect.TypeOf(xnappducontentsv1.XnRemovalResponseIEsValue_IdCriticalityDiagnostics{}),
		int64(v1.ProtocolIeIDInterfaceInstanceIndication): reflect.TypeOf(xnappducontentsv1.XnRemovalResponseIEsValue_IdInterfaceInstanceIndication{}),
	},
	"xn_removal_failure_ies": {
		int64(v1.ProtocolIeIDCause):                       reflect.TypeOf(xnappducontentsv1.XnRemovalFailureIEsValue_IdCause{}),
		int64(v1.ProtocolIeIDCriticalityDiagnostics):      reflect.TypeOf(xnappducontentsv1.XnRemovalFailureIEsValue_IdCriticalityDiagnostics{}),
		int64(v1.ProtocolIeIDInterfaceInstanceIndication): reflect.TypeOf(xnappducontentsv1.XnRemovalFailureIEsValue_IdInterfaceInstanceIndication{}),
	},
	"cell_activation_request_ies": {
		int64(v1.ProtocolIeIDServedCellsToActivate):         reflect.TypeOf(xnappducontentsv1.CellActivationRequestIEsValue_IdServedCellsToActivate{}),
		int64(v1.ProtocolIeIDActivationIDforCellActivation): reflect.TypeOf(xnappducontentsv1.CellActivationRequestIEsValue_IdActivationIdforCellActivation{}),
		int64(v1.ProtocolIeIDInterfaceInstanceIndication):   reflect.TypeOf(xnappducontentsv1.CellActivationRequestIEsValue_IdInterfaceInstanceIndication{}),
	},
	"cell_activation_response_ies": {
		int64(v1.ProtocolIeIDActivatedServedCells):          reflect.TypeOf(xnappducontentsv1.CellActivationResponseIEsValue_IdActivatedServedCells{}),
		int64(v1.ProtocolIeIDActivationIDforCellActivation): reflect.TypeOf(xnappducontentsv1.CellActivationResponseIEsValue_IdActivationIdforCellActivation{}),
		int64(v1.ProtocolIeIDCriticalityDiagnostics):        reflect.TypeOf(xnappducontentsv1.CellActivationResponseIEsValue_IdCriticalityDiagnostics{}),
		int64(v1.ProtocolIeIDInterfaceInstanceIndication):   reflect.TypeOf(xnappducontentsv1.CellActivationResponseIEsValue_IdInterfaceInstanceIndication{}),
	},
	"cell_activation_failure_ies": {
		int64(v1.ProtocolIeIDActivationIDforCellActivation): reflect.TypeOf(xnappducontentsv1.CellActivationFailureIEsValue_IdActivationIdforCellActivation{}),
		int64(v1.ProtocolIeIDCause):                         reflect.TypeOf(xnappducontentsv1.CellActivationFailureIEsValue_IdCause{}),
		int64(v1.ProtocolIeIDCriticalityDiagnostics):        reflect.TypeOf(xnappducontentsv1.CellActivationFailureIEsValue_IdCriticalityDiagnostics{}),
		int64(v1.ProtocolIeIDInterfaceInstanceIndication):   reflect.TypeOf(xnappducontentsv1.CellActivationFailureIEsValue_IdInterfaceInstanceIndication{}),
	},
	"reset_request_ies": {
		int64(v1.ProtocolIeIDResetRequestTypeInfo):        reflect.TypeOf(xnappducontentsv1.ResetRequestIEsValue_IdResetRequestTypeInfo{}),
		int64(v1.ProtocolIeIDCause):                       reflect.TypeOf(xnappducontentsv1.ResetRequestIEsValue_IdCause{}),
		int64(v1.ProtocolIeIDInterfaceInstanceIndication): reflect.TypeOf(xnappducontentsv1.ResetRequestIEsValue_IdInterfaceInstanceIndication{}),
	},
	"reset_response_ies": {
		int64(v1.ProtocolIeIDResetResponseTypeInfo):       reflect.TypeOf(xnappducontentsv1.ResetResponseIEsValue_IdResetResponseTypeInfo{}),
		int64(v1.ProtocolIeIDCriticalityDiagnostics):      reflect.TypeOf(xnappducontentsv1.ResetResponseIEsValue_IdCriticalityDiagnostics{}),
		int64(v1.ProtocolIeIDInterfaceInstanceIndication): reflect.TypeOf(xnappducontentsv1.ResetResponseIEsValue_IdInterfaceInstanceIndication{}),
	},
	"error_indication_ies": {
		int64(v1.ProtocolIeIDoldNGRANnodeUEXnAPID):        reflect.TypeOf(xnappducontentsv1.ErrorIndicationIEsValue_IdOldNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDnewNGRANnodeUEXnAPID):        reflect.TypeOf(xnappducontentsv1.ErrorIndicationIEsValue_IdNewNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDCause):                       reflect.TypeOf(xnappducontentsv1.ErrorIndicationIEsValue_IdCause{}),
		int64(v1.ProtocolIeIDCriticalityDiagnostics):      reflect.TypeOf(xnappducontentsv1.ErrorIndicationIEsValue_IdCriticalityDiagnostics{}),
		int64(v1.ProtocolIeIDInterfaceInstanceIndication): reflect.TypeOf(xnappducontentsv1.ErrorIndicationIEsValue_IdInterfaceInstanceIndication{}),
	},
	"trace_start_ies": {
		int64(v1.ProtocolIeIDMNGRANnodeUEXnAPID): reflect.TypeOf(xnappducontentsv1.TraceStartIesValue_IdMNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDSNGRANnodeUEXnAPID): reflect.TypeOf(xnappducontentsv1.TraceStartIesValue_IdSNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDTraceActivation):    reflect.TypeOf(xnappducontentsv1.TraceStartIesValue_IdTraceActivation{}),
	},
	"deactivate_trace_ies": {
		int64(v1.ProtocolIeIDMNGRANnodeUEXnAPID): reflect.TypeOf(xnappducontentsv1.DeactivateTraceIesValue_IdMNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDSNGRANnodeUEXnAPID): reflect.TypeOf(xnappducontentsv1.DeactivateTraceIesValue_IdSNgRannodeUexnApid{}),
		int64(v1.ProtocolIeIDNGRANTraceID):       reflect.TypeOf(xnappducontentsv1.DeactivateTraceIesValue_IdNgRantraceId{}),
	},
	"handover_report_ies": {
		int64(v1.ProtocolIeIDHandoverReportType):     reflect.TypeOf(xnappducontentsv1.HandoverReportIEsValue_IdHandoverReportType{}),
		int64(v1.ProtocolIeIDHandoverCause):          reflect.TypeOf(xnappducontentsv1.HandoverReportIEsValue_IdHandoverCause{}),
		int64(v1.ProtocolIeIDSourceCellCGI):          reflect.TypeOf(xnappducontentsv1.HandoverReportIEsValue_IdSourceCellCgi{}),
		int64(v1.ProtocolIeIDTargetCellCGI):          reflect.TypeOf(xnappducontentsv1.HandoverReportIEsValue_IdTargetCellCgi{}),
		int64(v1.ProtocolIeIDReEstablishmentCellCGI): reflect.TypeOf(xnappducontentsv1.HandoverReportIEsValue_IdReEstablishmentCellCgi{}),
		int64(v1.ProtocolIeIDTargetCellinEUTRAN):     reflect.TypeOf(xnappducontentsv1.HandoverReportIEsValue_IdTargetCellinEutran{}),
		int64(v1.ProtocolIeIDSourceCellCRNTI):        reflect.TypeOf(xnappducontentsv1.HandoverReportIEsValue_IdSourceCellCrnti{}),
		int64(v1.ProtocolIeIDMobilityInformation):    reflect.TypeOf(xnappducontentsv1.HandoverReportIEsValue_IdMobilityInformation{}),
		int64(v1.ProtocolIeIDUERLFReportContainer):   reflect.TypeOf(xnappducontentsv1.HandoverReportIEsValue_IdUerlfreportContainer{}),
	},
	"resource_status_request_ies": {
		int64(v1.ProtocolIeIDNGRANNode1MeasurementID): reflect.TypeOf(xnappducontentsv1.ResourceStatusRequestIEsValue_IdNgranNode1MeasurementId{}),
		int64(v1.ProtocolIeIDNGRANNode2MeasurementID): reflect.TypeOf(xnappducontentsv1.ResourceStatusRequestIEsValue_IdNgranNode2MeasurementId{}),
		int64(v1.ProtocolIeIDRegistrationRequest):     reflect.TypeOf(xnappducontentsv1.ResourceStatusRequestIEsValue_IdRegistrationRequest{}),
		int64(v1.ProtocolIeIDReportCharacteristics):   reflect.TypeOf(xnappducontentsv1.ResourceStatusRequestIEsValue_IdReportCharacteristics{}),
		int64(v1.ProtocolIeIDCellToReport):            reflect.TypeOf(xnappducontentsv1.ResourceStatusRequestIEsValue_IdCellToReport{}),
		int64(v1.ProtocolIeIDReportingPeriodicity):    reflect.TypeOf(xnappducontentsv1.ResourceStatusRequestIEsValue_IdReportingPeriodicity{}),
	},
	"resource_status_response_ies": {
		int64(v1.ProtocolIeIDNGRANNode1MeasurementID): reflect.TypeOf(xnappducontentsv1.ResourceStatusResponseIEsValue_IdNgranNode1MeasurementId{}),
		int64(v1.ProtocolIeIDNGRANNode2MeasurementID): reflect.TypeOf(xnappducontentsv1.ResourceStatusResponseIEsValue_IdNgranNode2MeasurementId{}),
		int64(v1.ProtocolIeIDCriticalityDiagnostics):  reflect.TypeOf(xnappducontentsv1.ResourceStatusResponseIEsValue_IdCriticalityDiagnostics{}),
	},
	"resource_status_failure_ies": {
		int64(v1.ProtocolIeIDNGRANNode1MeasurementID): reflect.TypeOf(xnappducontentsv1.ResourceStatusFailureIEsValue_IdNgranNode1MeasurementId{}),
		int64(v1.ProtocolIeIDNGRANNode2MeasurementID): reflect.TypeOf(xnappducontentsv1.ResourceStatusFailureIEsValue_IdNgranNode2MeasurementId{}),
		int64(v1.ProtocolIeIDCause):                   reflect.TypeOf(xnappducontentsv1.ResourceStatusFailureIEsValue_IdCause{}),
		int64(v1.ProtocolIeIDCriticalityDiagnostics):  reflect.TypeOf(xnappducontentsv1.ResourceStatusFailureIEsValue_IdCriticalityDiagnostics{}),
	},
	"resource_status_update_ies": {
		int64(v1.ProtocolIeIDNGRANNode1MeasurementID): reflect.TypeOf(xnappducontentsv1.ResourceStatusUpdateIEsValue_IdNgranNode1MeasurementId{}),
		int64(v1.ProtocolIeIDNGRANNode2MeasurementID): reflect.TypeOf(xnappducontentsv1.ResourceStatusUpdateIEsValue_IdNgranNode2MeasurementId{}),
		int64(v1.ProtocolIeIDCellMeasurementResult):   reflect.TypeOf(xnappducontentsv1.ResourceStatusUpdateIEsValue_IdCellMeasurementResult{}),
	},
	"mobility_change_request_ies": {
		int64(v1.ProtocolIeIDNGRANnode1CellID):                     reflect.TypeOf(xnappducontentsv1.MobilityChangeRequestIEsValue_IdNgRannode1CellId{}),
		int64(v1.ProtocolIeIDNGRANnode2CellID):                     reflect.TypeOf(xnappducontentsv1.MobilityChangeRequestIEsValue_IdNgRannode2CellId{}),
		int64(v1.ProtocolIeIDNGRANnode1MobilityParameters):         reflect.TypeOf(xnappducontentsv1.MobilityChangeRequestIEsValue_IdNgRannode1MobilityParameters{}),
		int64(v1.ProtocolIeIDNGRANnode2ProposedMobilityParameters): reflect.TypeOf(xnappducontentsv1.MobilityChangeRequestIEsValue_IdNgRannode2ProposedMobilityParameters{}),
		int64(v1.ProtocolIeIDCause):                                reflect.TypeOf(xnappducontentsv1.MobilityChangeRequestIEsValue_IdCause{}),
	},
	"mobility_change_acknowledge_ies": {
		int64(v1.ProtocolIeIDNGRANnode1CellID):       reflect.TypeOf(xnappducontentsv1.MobilityChangeAcknowledgeIEsValue_IdNgRannode1CellId{}),
		int64(v1.ProtocolIeIDNGRANnode2CellID):       reflect.TypeOf(xnappducontentsv1.MobilityChangeAcknowledgeIEsValue_IdNgRannode2CellId{}),
		int64(v1.ProtocolIeIDCriticalityDiagnostics): reflect.TypeOf(xnappducontentsv1.MobilityChangeAcknowledgeIEsValue_IdCriticalityDiagnostics{}),
	},
	"mobility_change_failure_ies": {
		int64(v1.ProtocolIeIDNGRANnode1CellID):                    reflect.TypeOf(xnappducontentsv1.MobilityChangeFailureIEsValue_IdNgRannode1CellId{}),
		int64(v1.ProtocolIeIDNGRANnode2CellID):                    reflect.TypeOf(xnappducontentsv1.MobilityChangeFailureIEsValue_IdNgRannode2CellId{}),
		int64(v1.ProtocolIeIDCause):                               reflect.TypeOf(xnappducontentsv1.MobilityChangeFailureIEsValue_IdCause{}),
		int64(v1.ProtocolIeIDMobilityParametersModificationRange): reflect.TypeOf(xnappducontentsv1.MobilityChangeFailureIEsValue_IdMobilityParametersModificationRange{}),
		int64(v1.ProtocolIeIDCriticalityDiagnostics):              reflect.TypeOf(xnappducontentsv1.MobilityChangeFailureIEsValue_IdCriticalityDiagnostics{}),
	},
	"bplmn_id_info_nr_item_ext_ies": {
		int64(v1.ProtocolIeIDConfiguredTACIndication): reflect.TypeOf(xnapiesv1.BplmnIDInfoNRItemExtIesExtension_IdConfiguredTacindication{}),
		int64(v1.ProtocolIeIDNPNBroadcastInformation): reflect.TypeOf(xnapiesv1.BplmnIDInfoNRItemExtIesExtension_IdNpnBroadcastInformation{}),
	},
	"broadcast_plmnin_taisupport_item_ext_ies": {
		int64(v1.ProtocolIeIDNPNSupport):                  reflect.TypeOf(xnapiesv1.BroadcastPlmninTaisupportItemExtIesExtension_IdNpnSupport{}),
		int64(v1.ProtocolIeIDExtendedTAISliceSupportList): reflect.TypeOf(xnapiesv1.BroadcastPlmninTaisupportItemExtIesExtension_IdExtendedTaisliceSupportList{}),
	},
	"xn_uaddress_infoper_pdusession_item_ext_ies": {
		int64(v1.ProtocolIeIDSecondarydataForwardingInfoFromTargetList): reflect.TypeOf(xnapiesv1.XnUaddressInfoperPdusessionItemExtIesExtension_IdSecondarydataForwardingInfoFromTargetList{}),
		int64(v1.ProtocolIeIDDRBIDstakenintouse):                        reflect.TypeOf(xnapiesv1.XnUaddressInfoperPdusessionItemExtIesExtension_IdDrbIdsTakenintouse{}),
		int64(v1.ProtocolIeIDdataForwardingInfoFromTargetEUTRANnode):    reflect.TypeOf(xnapiesv1.XnUaddressInfoperPdusessionItemExtIesExtension_IdDataForwardingInfoFromTargetEUtrannode{}),
	},
	"dynamic5_qidescriptor_ext_ies": {
		int64(v1.ProtocolIeIDExtendedPacketDelayBudget):   reflect.TypeOf(xnapiesv1.Dynamic5QidescriptorExtIesExtension_IdExtendedPacketDelayBudget{}),
		int64(v1.ProtocolIeIDCNPacketDelayBudgetDownlink): reflect.TypeOf(xnapiesv1.Dynamic5QidescriptorExtIesExtension_IdCnpacketDelayBudgetDownlink{}),
		int64(v1.ProtocolIeIDCNPacketDelayBudgetUplink):   reflect.TypeOf(xnapiesv1.Dynamic5QidescriptorExtIesExtension_IdCnpacketDelayBudgetUplink{}),
	},
	"mobility_restriction_list_ext_ies": {
		int64(v1.ProtocolIeIDLastEUTRANPLMNIdentity):          reflect.TypeOf(xnapiesv1.MobilityRestrictionListExtIesExtension_IdLastEUtranplmnidentity{}),
		int64(v1.ProtocolIeIDCNTypeRestrictionsForServing):    reflect.TypeOf(xnapiesv1.MobilityRestrictionListExtIesExtension_IdCntypeRestrictionsForServing{}),
		int64(v1.ProtocolIeIDCNTypeRestrictionsForEquivalent): reflect.TypeOf(xnapiesv1.MobilityRestrictionListExtIesExtension_IdCntypeRestrictionsForEquivalent{}),
		int64(v1.ProtocolIeIDNPNMobilityInformation):          reflect.TypeOf(xnapiesv1.MobilityRestrictionListExtIesExtension_IdNpnmobilityInformation{}),
	},
	"non_dynamic5_qidescriptor_ext_ies": {
		int64(v1.ProtocolIeIDCNPacketDelayBudgetDownlink): reflect.TypeOf(xnapiesv1.NonDynamic5QidescriptorExtIesExtension_IdCnpacketDelayBudgetDownlink{}),
		int64(v1.ProtocolIeIDCNPacketDelayBudgetUplink):   reflect.TypeOf(xnapiesv1.NonDynamic5QidescriptorExtIesExtension_IdCnpacketDelayBudgetUplink{}),
	},
	"ng_e_nb_radio_resource_status_ext_ies": {
		int64(v1.ProtocolIeIDDLschedulingPDCCHCCEusage): reflect.TypeOf(xnapiesv1.NgeNbRadioResourceStatusExtIesExtension_IdDlSchedulingPdcchCceUsage{}),
		int64(v1.ProtocolIeIDULschedulingPDCCHCCEusage): reflect.TypeOf(xnapiesv1.NgeNbRadioResourceStatusExtIesExtension_IdUlSchedulingPdcchCceUsage{}),
	},
	"nrmode_info_fdd_ext_ies": {
		int64(v1.ProtocolIeIDULCarrierList): reflect.TypeOf(xnapiesv1.NrmodeInfoFddExtIesExtension_IdUlcarrierList{}),
		int64(v1.ProtocolIeIDDLCarrierList): reflect.TypeOf(xnapiesv1.NrmodeInfoFddExtIesExtension_IdDlcarrierList{}),
	},
	"nrmode_info_tdd_ext_ies": {
		int64(v1.ProtocolIeIDIntendedTDDDLULConfigurationNR): reflect.TypeOf(xnapiesv1.NrmodeInfoTddExtIesExtension_IdIntendedTddDlUlconfigurationNr{}),
		int64(v1.ProtocolIeIDTDDULDLConfigurationCommonNR):   reflect.TypeOf(xnapiesv1.NrmodeInfoTddExtIesExtension_IdTdduldlconfigurationCommonNr{}),
		int64(v1.ProtocolIeIDCarrierList):                    reflect.TypeOf(xnapiesv1.NrmodeInfoTddExtIesExtension_IdCarrierList{}),
	},
	"pdusession_resources_to_be_setup_item_ext_ies": {
		int64(v1.ProtocolIeIDAdditionalULNGUTNLatUPFList):          reflect.TypeOf(xnapiesv1.PdusessionResourcesToBeSetupItemExtIesExtension_IdAdditionalUlNgUTnlatUpfList{}),
		int64(v1.ProtocolIeIDPDUSessionCommonNetworkInstance):      reflect.TypeOf(xnapiesv1.PdusessionResourcesToBeSetupItemExtIesExtension_IdPdusessionCommonNetworkInstance{}),
		int64(v1.ProtocolIeIDRedundantULNGUTNLatUPF):               reflect.TypeOf(xnapiesv1.PdusessionResourcesToBeSetupItemExtIesExtension_IdRedundantUlNgUTnlatUpf{}),
		int64(v1.ProtocolIeIDAdditionalRedundantULNGUTNLatUPFList): reflect.TypeOf(xnapiesv1.PdusessionResourcesToBeSetupItemExtIesExtension_IdAdditionalRedundantUlNgUTnlatUpfList{}),
		int64(v1.ProtocolIeIDRedundantCommonNetworkInstance):       reflect.TypeOf(xnapiesv1.PdusessionResourcesToBeSetupItemExtIesExtension_IdRedundantCommonNetworkInstance{}),
		int64(v1.ProtocolIeIDRedundantPDUSessionInformation):       reflect.TypeOf(xnapiesv1.PdusessionResourcesToBeSetupItemExtIesExtension_IdRedundantPdusessionInformation{}),
	},
	"pdusession_resource_setup_info_snterminated_ext_ies": {
		int64(v1.ProtocolIeIDSecurityResult):                  reflect.TypeOf(xnapiesv1.PdusessionResourceSetupInfoSNterminatedExtIesExtension_IdSecurityResult{}),
		int64(v1.ProtocolIeIDPDUSessionCommonNetworkInstance): reflect.TypeOf(xnapiesv1.PdusessionResourceSetupInfoSNterminatedExtIesExtension_IdPdusessionCommonNetworkInstance{}),
		int64(v1.ProtocolIeIDDefaultDRBAllowed):               reflect.TypeOf(xnapiesv1.PdusessionResourceSetupInfoSNterminatedExtIesExtension_IdDefaultDrbAllowed{}),
		int64(v1.ProtocolIeIDSplitSessionIndicator):           reflect.TypeOf(xnapiesv1.PdusessionResourceSetupInfoSNterminatedExtIesExtension_IdSplitSessionIndicator{}),
		int64(v1.ProtocolIeIDNonGBRResourcesOffered):          reflect.TypeOf(xnapiesv1.PdusessionResourceSetupInfoSNterminatedExtIesExtension_IdNonGbrresourcesOffered{}),
		int64(v1.ProtocolIeIDRedundantULNGUTNLatUPF):          reflect.TypeOf(xnapiesv1.PdusessionResourceSetupInfoSNterminatedExtIesExtension_IdRedundantUlNgUTnlatUpf{}),
		int64(v1.ProtocolIeIDRedundantCommonNetworkInstance):  reflect.TypeOf(xnapiesv1.PdusessionResourceSetupInfoSNterminatedExtIesExtension_IdRedundantCommonNetworkInstance{}),
		int64(v1.ProtocolIeIDRedundantPDUSessionInformation):  reflect.TypeOf(xnapiesv1.PdusessionResourceSetupInfoSNterminatedExtIesExtension_IdRedundantPdusessionInformation{}),
	},
	"qo_sflows_to_be_setup_list_setup_snterminated_item_ext_ies": {
		int64(v1.ProtocolIeIDTSCTrafficCharacteristics): reflect.TypeOf(xnapiesv1.QoSflowsToBeSetupListSetupSNterminatedItemExtIesExtension_IdTsctrafficCharacteristics{}),
		int64(v1.ProtocolIeIDRedundantQoSFlowIndicator): reflect.TypeOf(xnapiesv1.QoSflowsToBeSetupListSetupSNterminatedItemExtIesExtension_IdRedundantQoSflowIndicator{}),
	},
	"pdusession_resource_setup_response_info_snterminated_ext_ies": {
		int64(v1.ProtocolIeIDDRBIDstakenintouse):       reflect.TypeOf(xnapiesv1.PdusessionResourceSetupResponseInfoSNterminatedExtIesExtension_IdDrbIdsTakenintouse{}),
		int64(v1.ProtocolIeIDRedundantDLNGUTNLatNGRAN): reflect.TypeOf(xnapiesv1.PdusessionResourceSetupResponseInfoSNterminatedExtIesExtension_IdRedundantDlNgUTnlatNgRan{}),
		int64(v1.ProtocolIeIDUsedRSNInformation):       reflect.TypeOf(xnapiesv1.PdusessionResourceSetupResponseInfoSNterminatedExtIesExtension_IdUsedRsninformation{}),
	},
	"drbs_to_be_setup_list_setup_response_snterminated_item_ext_ies": {
		int64(v1.ProtocolIeIDAdditionalPDCPDuplicationTNLList): reflect.TypeOf(xnapiesv1.DrbsToBeSetupListSetupResponseSNterminatedItemExtIesExtension_IdAdditionalPdcpDuplicationTnlList{}),
		int64(v1.ProtocolIeIDRLCDuplicationInformation):        reflect.TypeOf(xnapiesv1.DrbsToBeSetupListSetupResponseSNterminatedItemExtIesExtension_IdRlcduplicationInformation{}),
	},
	"qo_sflows_mappedto_drb_setup_response_snterminated_item_ext_ies": {
		int64(v1.ProtocolIeIDCurrentQoSParaSetIndex):      reflect.TypeOf(xnapiesv1.QoSflowsMappedtoDrbSetupResponseSNterminatedItemExtIesExtension_IdCurrentQoSparaSetIndex{}),
		int64(v1.ProtocolIeIDSourceDLForwardingIPAddress): reflect.TypeOf(xnapiesv1.QoSflowsMappedtoDrbSetupResponseSNterminatedItemExtIesExtension_IdSourceDlforwardingIpaddress{}),
	},
	"drbs_to_be_setup_list_setup_mnterminated_item_ext_ies": {
		int64(v1.ProtocolIeIDAdditionalPDCPDuplicationTNLList): reflect.TypeOf(xnapiesv1.DrbsToBeSetupListSetupMNterminatedItemExtIesExtension_IdAdditionalPdcpDuplicationTnlList{}),
		int64(v1.ProtocolIeIDRLCDuplicationInformation):        reflect.TypeOf(xnapiesv1.DrbsToBeSetupListSetupMNterminatedItemExtIesExtension_IdRlcduplicationInformation{}),
	},
	"drbs_admitted_list_setup_response_mnterminated_item_ext_ies": {
		int64(v1.ProtocolIeIDAdditionalPDCPDuplicationTNLList):             reflect.TypeOf(xnapiesv1.DrbsAdmittedListSetupResponseMNterminatedItemExtIesExtension_IdAdditionalPdcpDuplicationTnlList{}),
		int64(v1.ProtocolIeIDQoSFlowsMappedtoDRBSetupResponseMNterminated): reflect.TypeOf(xnapiesv1.DrbsAdmittedListSetupResponseMNterminatedItemExtIesExtension_IdQoSflowsMappedtoDrbSetupResponseMnterminated{}),
	},
	"pdusession_resource_modification_info_snterminated_ext_ies": {
		int64(v1.ProtocolIeIDPDUSessionCommonNetworkInstance): reflect.TypeOf(xnapiesv1.PdusessionResourceModificationInfoSNterminatedExtIesExtension_IdPdusessionCommonNetworkInstance{}),
		int64(v1.ProtocolIeIDDefaultDRBAllowed):               reflect.TypeOf(xnapiesv1.PdusessionResourceModificationInfoSNterminatedExtIesExtension_IdDefaultDrbAllowed{}),
		int64(v1.ProtocolIeIDNonGBRResourcesOffered):          reflect.TypeOf(xnapiesv1.PdusessionResourceModificationInfoSNterminatedExtIesExtension_IdNonGbrresourcesOffered{}),
		int64(v1.ProtocolIeIDRedundantULNGUTNLatUPF):          reflect.TypeOf(xnapiesv1.PdusessionResourceModificationInfoSNterminatedExtIesExtension_IdRedundantUlNgUTnlatUpf{}),
		int64(v1.ProtocolIeIDRedundantCommonNetworkInstance):  reflect.TypeOf(xnapiesv1.PdusessionResourceModificationInfoSNterminatedExtIesExtension_IdRedundantCommonNetworkInstance{}),
		int64(v1.ProtocolIeIDSecurityIndication):              reflect.TypeOf(xnapiesv1.PdusessionResourceModificationInfoSNterminatedExtIesExtension_IdSecurityIndication{}),
	},
	"qo_sflows_to_be_setup_list_modified_snterminated_item_ext_ies": {
		int64(v1.ProtocolIeIDTSCTrafficCharacteristics): reflect.TypeOf(xnapiesv1.QoSflowsToBeSetupListModifiedSNterminatedItemExtIesExtension_IdTsctrafficCharacteristics{}),
		int64(v1.ProtocolIeIDRedundantQoSFlowIndicator): reflect.TypeOf(xnapiesv1.QoSflowsToBeSetupListModifiedSNterminatedItemExtIesExtension_IdRedundantQoSflowIndicator{}),
	},
	"pdusession_resource_modification_response_info_snterminated_ext_ies": {
		int64(v1.ProtocolIeIDDRBIDstakenintouse):       reflect.TypeOf(xnapiesv1.PdusessionResourceModificationResponseInfoSNterminatedExtIesExtension_IdDrbIdsTakenintouse{}),
		int64(v1.ProtocolIeIDRedundantDLNGUTNLatNGRAN): reflect.TypeOf(xnapiesv1.PdusessionResourceModificationResponseInfoSNterminatedExtIesExtension_IdRedundantDlNgUTnlatNgRan{}),
		int64(v1.ProtocolIeIDSecurityResult):           reflect.TypeOf(xnapiesv1.PdusessionResourceModificationResponseInfoSNterminatedExtIesExtension_IdSecurityResult{}),
	},
	"drbs_to_be_modified_list_modification_response_snterminated_item_ext_ies": {
		int64(v1.ProtocolIeIDAdditionalPDCPDuplicationTNLList): reflect.TypeOf(xnapiesv1.DrbsToBeModifiedListModificationResponseSNterminatedItemExtIesExtension_IdAdditionalPdcpDuplicationTnlList{}),
		int64(v1.ProtocolIeIDRLCDuplicationInformation):        reflect.TypeOf(xnapiesv1.DrbsToBeModifiedListModificationResponseSNterminatedItemExtIesExtension_IdRlcduplicationInformation{}),
		int64(v1.ProtocolIeIDsecondarySNULPDCPUPTNLInfo):       reflect.TypeOf(xnapiesv1.DrbsToBeModifiedListModificationResponseSNterminatedItemExtIesExtension_IdSecondarySnUlPdcpUpTnlinfo{}),
		int64(v1.ProtocolIeIDpdcpDuplicationConfiguration):     reflect.TypeOf(xnapiesv1.DrbsToBeModifiedListModificationResponseSNterminatedItemExtIesExtension_IdPdcpDuplicationConfiguration{}),
		int64(v1.ProtocolIeIDduplicationActivation):            reflect.TypeOf(xnapiesv1.DrbsToBeModifiedListModificationResponseSNterminatedItemExtIesExtension_IdDuplicationActivation{}),
	},
	"drbs_to_be_modified_list_modification_mnterminated_item_ext_ies": {
		int64(v1.ProtocolIeIDAdditionalPDCPDuplicationTNLList): reflect.TypeOf(xnapiesv1.DrbsToBeModifiedListModificationMNterminatedItemExtIesExtension_IdAdditionalPdcpDuplicationTnlList{}),
		int64(v1.ProtocolIeIDRLCDuplicationInformation):        reflect.TypeOf(xnapiesv1.DrbsToBeModifiedListModificationMNterminatedItemExtIesExtension_IdRlcduplicationInformation{}),
	},
	"drbs_admitted_list_modification_response_mnterminated_item_ext_ies": {
		int64(v1.ProtocolIeIDAdditionalPDCPDuplicationTNLList):             reflect.TypeOf(xnapiesv1.DrbsAdmittedListModificationResponseMNterminatedItemExtIesExtension_IdAdditionalPdcpDuplicationTnlList{}),
		int64(v1.ProtocolIeIDQoSFlowsMappedtoDRBSetupResponseMNterminated): reflect.TypeOf(xnapiesv1.DrbsAdmittedListModificationResponseMNterminatedItemExtIesExtension_IdQoSflowsMappedtoDrbSetupResponseMnterminated{}),
	},
	"drbs_to_be_setup_list_mod_rqd_snterminated_item_ext_ies": {
		int64(v1.ProtocolIeIDAdditionalPDCPDuplicationTNLList): reflect.TypeOf(xnapiesv1.DrbsToBeSetupListModRqdSNterminatedItemExtIesExtension_IdAdditionalPdcpDuplicationTnlList{}),
		int64(v1.ProtocolIeIDRLCDuplicationInformation):        reflect.TypeOf(xnapiesv1.DrbsToBeSetupListModRqdSNterminatedItemExtIesExtension_IdRlcduplicationInformation{}),
	},
	"drbs_to_be_modified_list_mod_rqd_snterminated_item_ext_ies": {
		int64(v1.ProtocolIeIDAdditionalPDCPDuplicationTNLList): reflect.TypeOf(xnapiesv1.DrbsToBeModifiedListModRqdSNterminatedItemExtIesExtension_IdAdditionalPdcpDuplicationTnlList{}),
		int64(v1.ProtocolIeIDRLCDuplicationInformation):        reflect.TypeOf(xnapiesv1.DrbsToBeModifiedListModRqdSNterminatedItemExtIesExtension_IdRlcduplicationInformation{}),
	},
	"qo_sflow_level_qo_sparameters_ext_ies": {
		int64(v1.ProtocolIeIDQoSMonitoringRequest):            reflect.TypeOf(xnapiesv1.QoSflowLevelQoSparametersExtIesExtension_IdQoSmonitoringRequest{}),
		int64(v1.ProtocolIeIDQosMonitoringReportingFrequency): reflect.TypeOf(xnapiesv1.QoSflowLevelQoSparametersExtIesExtension_IdQosMonitoringReportingFrequency{}),
		int64(v1.ProtocolIeIDQoSMonitoringDisabled):           reflect.TypeOf(xnapiesv1.QoSflowLevelQoSparametersExtIesExtension_IdQoSmonitoringDisabled{}),
	},
	"qo_sflows_to_be_setup_item_ext_ies": {
		int64(v1.ProtocolIeIDTSCTrafficCharacteristics): reflect.TypeOf(xnapiesv1.QoSflowsToBeSetupItemExtIesExtension_IdTsctrafficCharacteristics{}),
		int64(v1.ProtocolIeIDRedundantQoSFlowIndicator): reflect.TypeOf(xnapiesv1.QoSflowsToBeSetupItemExtIesExtension_IdRedundantQoSflowIndicator{}),
	},
	"served_cell_information_e_utra_ext_ies": {
		int64(v1.ProtocolIeIDBPLMNIDInfoEUTRA):    reflect.TypeOf(xnapiesv1.ServedCellInformationEUTraExtIesExtension_IdBplmnIdInfoEutra{}),
		int64(v1.ProtocolIeIDNPRACHConfiguration): reflect.TypeOf(xnapiesv1.ServedCellInformationEUTraExtIesExtension_IdNprachconfiguration{}),
	},
	"served_cell_information_e_utra_fddinfo_ext_ies": {
		int64(v1.ProtocolIeIDOffsetOfNbiotChannelNumberToDLEARFCN): reflect.TypeOf(xnapiesv1.ServedCellInformationEUTraFDdinfoExtIesExtension_IdOffsetOfNbiotChannelNumberToDlEarfcn{}),
		int64(v1.ProtocolIeIDOffsetOfNbiotChannelNumberToULEARFCN): reflect.TypeOf(xnapiesv1.ServedCellInformationEUTraFDdinfoExtIesExtension_IdOffsetOfNbiotChannelNumberToUlEarfcn{}),
	},
	"served_cell_information_e_utra_tddinfo_ext_ies": {
		int64(v1.ProtocolIeIDOffsetOfNbiotChannelNumberToDLEARFCN): reflect.TypeOf(xnapiesv1.ServedCellInformationEUTraTDdinfoExtIesExtension_IdOffsetOfNbiotChannelNumberToDlEarfcn{}),
		int64(v1.ProtocolIeIDNBIoTULDLAlignmentOffset):             reflect.TypeOf(xnapiesv1.ServedCellInformationEUTraTDdinfoExtIesExtension_IdNbioTUlDlAlignmentOffset{}),
	},
	"served_cell_information_nr_ext_ies": {
		int64(v1.ProtocolIeIDBPLMNIDInfoNR):               reflect.TypeOf(xnapiesv1.ServedCellInformationNRExtIesExtension_IdBplmnIdInfoNr{}),
		int64(v1.ProtocolIeIDConfiguredTACIndication):     reflect.TypeOf(xnapiesv1.ServedCellInformationNRExtIesExtension_IdConfiguredTacindication{}),
		int64(v1.ProtocolIeIDSSBPositionsInBurst):         reflect.TypeOf(xnapiesv1.ServedCellInformationNRExtIesExtension_IdSsbPositionsInBurst{}),
		int64(v1.ProtocolIeIDNRCellPRACHConfig):           reflect.TypeOf(xnapiesv1.ServedCellInformationNRExtIesExtension_IdNrcellPrachconfig{}),
		int64(v1.ProtocolIeIDNPNBroadcastInformation):     reflect.TypeOf(xnapiesv1.ServedCellInformationNRExtIesExtension_IdNpnBroadcastInformation{}),
		int64(v1.ProtocolIeIDCSIRSTransmissionIndication): reflect.TypeOf(xnapiesv1.ServedCellInformationNRExtIesExtension_IdCsiRstransmissionIndication{}),
		int64(v1.ProtocolIeIDSFNOffset):                   reflect.TypeOf(xnapiesv1.ServedCellInformationNRExtIesExtension_IdSfnOffset{}),
	},
	"ssbarea_radio_resource_status_list_item_ext_ies": {
		int64(v1.ProtocolIeIDDLschedulingPDCCHCCEusage): reflect.TypeOf(xnapiesv1.SsbareaRadioResourceStatusListItemExtIesExtension_IdDlSchedulingPdcchCceUsage{}),
		int64(v1.ProtocolIeIDULschedulingPDCCHCCEusage): reflect.TypeOf(xnapiesv1.SsbareaRadioResourceStatusListItemExtIesExtension_IdUlSchedulingPdcchCceUsage{}),
	},
	"sul_information_ext_ies": {
		int64(v1.ProtocolIeIDCarrierList):          reflect.TypeOf(xnapiesv1.SulInformationExtIesExtension_IdCarrierList{}),
		int64(v1.ProtocolIeIDFrequencyShift7p5khz): reflect.TypeOf(xnapiesv1.SulInformationExtIesExtension_IdFrequencyShift7P5Khz{}),
	},
	"trace_activation_ext_ies": {
		int64(v1.ProtocolIeIDTraceCollectionEntityURI): reflect.TypeOf(xnapiesv1.TraceActivationExtIesExtension_IdTraceCollectionEntityUri{}),
		int64(v1.ProtocolIeIDMDTConfiguration):         reflect.TypeOf(xnapiesv1.TraceActivationExtIesExtension_IdMdtConfiguration{}),
	},
	"uecontext_info_retr_uectxt_resp_ext_ies": {
		int64(v1.ProtocolIeIDFiveGCMobilityRestrictionListContainer): reflect.TypeOf(xnapiesv1.UecontextInfoRetrUectxtRespExtIesExtension_IdFiveGcmobilityRestrictionListContainer{}),
		int64(v1.ProtocolIeIDNRUESidelinkAggregateMaximumBitRate):    reflect.TypeOf(xnapiesv1.UecontextInfoRetrUectxtRespExtIesExtension_IdNruesidelinkAggregateMaximumBitRate{}),
		int64(v1.ProtocolIeIDLTEUESidelinkAggregateMaximumBitRate):   reflect.TypeOf(xnapiesv1.UecontextInfoRetrUectxtRespExtIesExtension_IdLteuesidelinkAggregateMaximumBitRate{}),
		int64(v1.ProtocolIeIDUERadioCapabilityID):                    reflect.TypeOf(xnapiesv1.UecontextInfoRetrUectxtRespExtIesExtension_IdUeradioCapabilityId{}),
	},
	"im_values": {
		int64(v1.ProcedureCodeIDxnSetup): reflect.TypeOf(xnappdudescriptionsv1.InitiatingMessageXnApElementaryProcedures_XnSetupRequest{}),
	},
	"so_values": {
		int64(v1.ProcedureCodeIDxnSetup): reflect.TypeOf(xnappdudescriptionsv1.SuccessfulOutcomeXnApElementaryProcedures_XnSetupResponse{}),
	},
	"uo_values": {
		int64(v1.ProcedureCodeIDxnSetup): reflect.TypeOf(xnappdudescriptionsv1.UnsuccessfulOutcomeXnApElementaryProcedures_XnSetupFailure{}),
	},
}
