// Code generated by protoc-gen-go. DO NOT EDIT.
// CriticalityDiagnostics-IE-Item.proto is a deprecated file.

package e2ctypes

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CriticalityDiagnostics_IE_ItemT struct {
	IECriticality        CriticalityT   `protobuf:"varint,1,opt,name=iECriticality,proto3,enum=e2ctypes.CriticalityT" json:"iECriticality,omitempty"`
	IE_ID                ProtocolIE_IDT `protobuf:"varint,2,opt,name=iE_ID,json=iEID,proto3,enum=e2ctypes.ProtocolIE_IDT" json:"iE_ID,omitempty"`
	TypeOfError          TypeOfErrorT   `protobuf:"varint,3,opt,name=typeOfError,proto3,enum=e2ctypes.TypeOfErrorT" json:"typeOfError,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CriticalityDiagnostics_IE_ItemT) Reset()         { *m = CriticalityDiagnostics_IE_ItemT{} }
func (m *CriticalityDiagnostics_IE_ItemT) String() string { return proto.CompactTextString(m) }
func (*CriticalityDiagnostics_IE_ItemT) ProtoMessage()    {}
func (*CriticalityDiagnostics_IE_ItemT) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc3645f145a66f3a, []int{0}
}

func (m *CriticalityDiagnostics_IE_ItemT) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CriticalityDiagnostics_IE_ItemT.Unmarshal(m, b)
}
func (m *CriticalityDiagnostics_IE_ItemT) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CriticalityDiagnostics_IE_ItemT.Marshal(b, m, deterministic)
}
func (m *CriticalityDiagnostics_IE_ItemT) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CriticalityDiagnostics_IE_ItemT.Merge(m, src)
}
func (m *CriticalityDiagnostics_IE_ItemT) XXX_Size() int {
	return xxx_messageInfo_CriticalityDiagnostics_IE_ItemT.Size(m)
}
func (m *CriticalityDiagnostics_IE_ItemT) XXX_DiscardUnknown() {
	xxx_messageInfo_CriticalityDiagnostics_IE_ItemT.DiscardUnknown(m)
}

var xxx_messageInfo_CriticalityDiagnostics_IE_ItemT proto.InternalMessageInfo

func (m *CriticalityDiagnostics_IE_ItemT) GetIECriticality() CriticalityT {
	if m != nil {
		return m.IECriticality
	}
	return CriticalityT_Criticality_reject
}

func (m *CriticalityDiagnostics_IE_ItemT) GetIE_ID() ProtocolIE_IDT {
	if m != nil {
		return m.IE_ID
	}
	return ProtocolIE_IDT_ProtocolIE_ID_id_Dummy
}

func (m *CriticalityDiagnostics_IE_ItemT) GetTypeOfError() TypeOfErrorT {
	if m != nil {
		return m.TypeOfError
	}
	return TypeOfErrorT_TypeOfError_not_understood
}

func init() {
	proto.RegisterType((*CriticalityDiagnostics_IE_ItemT)(nil), "e2ctypes.CriticalityDiagnostics_IE_Item_t")
}

func init() {
	proto.RegisterFile("CriticalityDiagnostics-IE-Item.proto", fileDescriptor_cc3645f145a66f3a)
}

var fileDescriptor_cc3645f145a66f3a = []byte{
	// 206 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x71, 0x2e, 0xca, 0x2c,
	0xc9, 0x4c, 0x4e, 0xcc, 0xc9, 0x2c, 0xa9, 0x74, 0xc9, 0x4c, 0x4c, 0xcf, 0xcb, 0x2f, 0x2e, 0xc9,
	0x4c, 0x2e, 0xd6, 0xf5, 0x74, 0xd5, 0xf5, 0x2c, 0x49, 0xcd, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0xe2, 0x48, 0x35, 0x4a, 0x2e, 0xa9, 0x2c, 0x48, 0x2d, 0x96, 0x12, 0x44, 0x52, 0x0f, 0x91,
	0x94, 0x12, 0x0e, 0x00, 0x51, 0xc9, 0xf9, 0x39, 0x20, 0x3d, 0x2e, 0x50, 0x41, 0xc1, 0x90, 0xca,
	0x82, 0x54, 0xff, 0x34, 0xd7, 0xa2, 0xa2, 0xfc, 0x22, 0x88, 0x90, 0xd2, 0x19, 0x46, 0x2e, 0x05,
	0xec, 0xb6, 0xc5, 0x7b, 0xba, 0xc6, 0x83, 0x6c, 0x8b, 0x2f, 0x11, 0xb2, 0xe5, 0xe2, 0xcd, 0x74,
	0x45, 0x52, 0x25, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x67, 0x24, 0xae, 0x07, 0x73, 0x81, 0x1e, 0x92,
	0x64, 0x7c, 0x49, 0x10, 0xaa, 0x6a, 0x21, 0x3d, 0x2e, 0xd6, 0x4c, 0xd7, 0x78, 0x4f, 0x17, 0x09,
	0x26, 0xb0, 0x36, 0x49, 0x84, 0x36, 0x84, 0x23, 0xe3, 0x3d, 0x5d, 0xe2, 0x4b, 0x82, 0x58, 0x32,
	0x5d, 0x3d, 0x5d, 0x84, 0x2c, 0xb9, 0xb8, 0x4b, 0x10, 0x0e, 0x95, 0x60, 0x46, 0xb7, 0x0c, 0xc9,
	0x17, 0xf1, 0x25, 0x41, 0xc8, 0x6a, 0x9d, 0x98, 0x77, 0x30, 0x32, 0x26, 0xb1, 0x81, 0xbd, 0x66,
	0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x32, 0x69, 0x3f, 0xd9, 0x47, 0x01, 0x00, 0x00,
}
