// Code generated by protoc-gen-go. DO NOT EDIT.
// CriticalityDiagnostics.proto is a deprecated file.

package e2ctypes

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CriticalityDiagnosticsT struct {
	ProcedureCode             ProcedureCodeT                   `protobuf:"varint,1,opt,name=procedureCode,proto3,enum=e2ctypes.ProcedureCodeT" json:"procedureCode,omitempty"`             // Deprecated: Do not use.
	TriggeringMessage         TriggeringMessageT               `protobuf:"varint,2,opt,name=triggeringMessage,proto3,enum=e2ctypes.TriggeringMessageT" json:"triggeringMessage,omitempty"` // Deprecated: Do not use.
	ProcedureCriticality      CriticalityT                     `protobuf:"varint,3,opt,name=procedureCriticality,proto3,enum=e2ctypes.CriticalityT" json:"procedureCriticality,omitempty"` // Deprecated: Do not use.
	RicRequestorID            *RICrequestIDT                   `protobuf:"bytes,4,opt,name=ricRequestorID,proto3" json:"ricRequestorID,omitempty"`                                         // Deprecated: Do not use.
	IEsCriticalityDiagnostics *CriticalityDiagnostics_IE_ListT `protobuf:"bytes,5,opt,name=iEsCriticalityDiagnostics,proto3" json:"iEsCriticalityDiagnostics,omitempty"`                   // Deprecated: Do not use.
	XXX_NoUnkeyedLiteral      struct{}                         `json:"-"`
	XXX_unrecognized          []byte                           `json:"-"`
	XXX_sizecache             int32                            `json:"-"`
}

func (m *CriticalityDiagnosticsT) Reset()         { *m = CriticalityDiagnosticsT{} }
func (m *CriticalityDiagnosticsT) String() string { return proto.CompactTextString(m) }
func (*CriticalityDiagnosticsT) ProtoMessage()    {}
func (*CriticalityDiagnosticsT) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae74d3e814df3ae7, []int{0}
}

func (m *CriticalityDiagnosticsT) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CriticalityDiagnosticsT.Unmarshal(m, b)
}
func (m *CriticalityDiagnosticsT) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CriticalityDiagnosticsT.Marshal(b, m, deterministic)
}
func (m *CriticalityDiagnosticsT) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CriticalityDiagnosticsT.Merge(m, src)
}
func (m *CriticalityDiagnosticsT) XXX_Size() int {
	return xxx_messageInfo_CriticalityDiagnosticsT.Size(m)
}
func (m *CriticalityDiagnosticsT) XXX_DiscardUnknown() {
	xxx_messageInfo_CriticalityDiagnosticsT.DiscardUnknown(m)
}

var xxx_messageInfo_CriticalityDiagnosticsT proto.InternalMessageInfo

// Deprecated: Do not use.
func (m *CriticalityDiagnosticsT) GetProcedureCode() ProcedureCodeT {
	if m != nil {
		return m.ProcedureCode
	}
	return ProcedureCodeT_ProcedureCode_id_dummy
}

// Deprecated: Do not use.
func (m *CriticalityDiagnosticsT) GetTriggeringMessage() TriggeringMessageT {
	if m != nil {
		return m.TriggeringMessage
	}
	return TriggeringMessageT_TriggeringMessage_initiating_message
}

// Deprecated: Do not use.
func (m *CriticalityDiagnosticsT) GetProcedureCriticality() CriticalityT {
	if m != nil {
		return m.ProcedureCriticality
	}
	return CriticalityT_Criticality_reject
}

// Deprecated: Do not use.
func (m *CriticalityDiagnosticsT) GetRicRequestorID() *RICrequestIDT {
	if m != nil {
		return m.RicRequestorID
	}
	return nil
}

// Deprecated: Do not use.
func (m *CriticalityDiagnosticsT) GetIEsCriticalityDiagnostics() *CriticalityDiagnostics_IE_ListT {
	if m != nil {
		return m.IEsCriticalityDiagnostics
	}
	return nil
}

func init() {
	proto.RegisterType((*CriticalityDiagnosticsT)(nil), "e2ctypes.CriticalityDiagnostics_t")
}

func init() { proto.RegisterFile("CriticalityDiagnostics.proto", fileDescriptor_ae74d3e814df3ae7) }

var fileDescriptor_ae74d3e814df3ae7 = []byte{
	// 284 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x51, 0x4b, 0xfb, 0x30,
	0x14, 0xc5, 0xc9, 0xfa, 0xff, 0x8b, 0x44, 0x1c, 0x2c, 0x0a, 0xcb, 0x86, 0xc2, 0x10, 0x1f, 0x86,
	0xb0, 0x3e, 0xd4, 0x6f, 0xb0, 0xb6, 0x0f, 0x05, 0x65, 0x52, 0x7c, 0x2f, 0xb5, 0x0b, 0xe1, 0xc2,
	0x58, 0x6a, 0x72, 0xf7, 0xb0, 0x0f, 0x26, 0xf8, 0xf1, 0xc4, 0x36, 0x23, 0xd9, 0x16, 0x5f, 0x73,
	0xef, 0xf9, 0x9d, 0x93, 0x73, 0xe9, 0x5d, 0xaa, 0x01, 0xa1, 0xa9, 0x37, 0x80, 0xfb, 0x0c, 0x6a,
	0xb9, 0x55, 0x06, 0xa1, 0x31, 0x71, 0xab, 0x15, 0x2a, 0x76, 0x29, 0x92, 0x06, 0xf7, 0xad, 0x30,
	0xd3, 0x9b, 0x37, 0xad, 0x1a, 0xb1, 0xde, 0x69, 0x91, 0xaa, 0xb5, 0xe8, 0xc7, 0xd3, 0x91, 0x27,
	0xb6, 0x4f, 0xac, 0x2c, 0x52, 0x2d, 0x3e, 0x77, 0xc2, 0x60, 0x91, 0xd9, 0xb7, 0xf1, 0xbb, 0x06,
	0x29, 0x85, 0x86, 0xad, 0x7c, 0x15, 0xc6, 0xd4, 0xf2, 0xa0, 0x7f, 0x0c, 0x9b, 0x2f, 0x8a, 0x7c,
	0xf1, 0x02, 0x06, 0xfb, 0xad, 0x87, 0xaf, 0x88, 0xf2, 0xf0, 0x62, 0x85, 0x2c, 0xa5, 0xd7, 0xad,
	0x9f, 0x8c, 0x93, 0x19, 0x99, 0x0f, 0x93, 0x49, 0x7c, 0x48, 0x1e, 0x1f, 0x05, 0xaf, 0x70, 0x39,
	0xe0, 0xa4, 0x3c, 0xd6, 0xb0, 0x15, 0x1d, 0xe1, 0x69, 0x44, 0x3e, 0xe8, 0x40, 0xf7, 0x0e, 0x74,
	0xf6, 0x0b, 0x0b, 0x3b, 0xd7, 0xb2, 0x15, 0xbd, 0x75, 0x0e, 0x2e, 0x3a, 0x8f, 0x3a, 0xe6, 0xd8,
	0x31, 0xbd, 0xa1, 0xa5, 0x05, 0x85, 0x2c, 0xa3, 0x43, 0x0d, 0x4d, 0xd9, 0x17, 0xab, 0x74, 0x91,
	0xf1, 0x7f, 0x33, 0x32, 0xbf, 0x4a, 0xb8, 0x43, 0xf9, 0xc5, 0x5b, 0xd6, 0x89, 0x86, 0x6d, 0xe8,
	0x04, 0x72, 0x13, 0xee, 0x92, 0xff, 0xef, 0x80, 0x4f, 0xc1, 0x6c, 0x7e, 0xe7, 0x45, 0x5e, 0xfd,
	0x1e, 0xc7, 0x5a, 0xfc, 0x0d, 0x5c, 0x46, 0xdf, 0x84, 0x7c, 0x5c, 0x74, 0x37, 0x7c, 0xfe, 0x09,
	0x00, 0x00, 0xff, 0xff, 0xea, 0x11, 0x87, 0xbc, 0x68, 0x02, 0x00, 0x00,
}
