// Code generated by protoc-gen-go. DO NOT EDIT.
// source: GlobalE2node-en-gNB-ID.proto

package e2ctypes

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GlobalE2NodeEnGNB_IDT struct {
	GlobalGNB_ID         *GlobalenGNB_IDT `protobuf:"bytes,1,opt,name=global_gNB_ID,json=globalGNBID,proto3" json:"global_gNB_ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GlobalE2NodeEnGNB_IDT) Reset()         { *m = GlobalE2NodeEnGNB_IDT{} }
func (m *GlobalE2NodeEnGNB_IDT) String() string { return proto.CompactTextString(m) }
func (*GlobalE2NodeEnGNB_IDT) ProtoMessage()    {}
func (*GlobalE2NodeEnGNB_IDT) Descriptor() ([]byte, []int) {
	return fileDescriptor_2620521589517d4f, []int{0}
}

func (m *GlobalE2NodeEnGNB_IDT) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GlobalE2NodeEnGNB_IDT.Unmarshal(m, b)
}
func (m *GlobalE2NodeEnGNB_IDT) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GlobalE2NodeEnGNB_IDT.Marshal(b, m, deterministic)
}
func (m *GlobalE2NodeEnGNB_IDT) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GlobalE2NodeEnGNB_IDT.Merge(m, src)
}
func (m *GlobalE2NodeEnGNB_IDT) XXX_Size() int {
	return xxx_messageInfo_GlobalE2NodeEnGNB_IDT.Size(m)
}
func (m *GlobalE2NodeEnGNB_IDT) XXX_DiscardUnknown() {
	xxx_messageInfo_GlobalE2NodeEnGNB_IDT.DiscardUnknown(m)
}

var xxx_messageInfo_GlobalE2NodeEnGNB_IDT proto.InternalMessageInfo

func (m *GlobalE2NodeEnGNB_IDT) GetGlobalGNB_ID() *GlobalenGNB_IDT {
	if m != nil {
		return m.GlobalGNB_ID
	}
	return nil
}

func init() {
	proto.RegisterType((*GlobalE2NodeEnGNB_IDT)(nil), "e2ctypes.GlobalE2node_en_gNB_ID_t")
}

func init() { proto.RegisterFile("GlobalE2node-en-gNB-ID.proto", fileDescriptor_2620521589517d4f) }

var fileDescriptor_2620521589517d4f = []byte{
	// 130 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x71, 0xcf, 0xc9, 0x4f,
	0x4a, 0xcc, 0x71, 0x35, 0xca, 0xcb, 0x4f, 0x49, 0xd5, 0x4d, 0xcd, 0xd3, 0x4d, 0xf7, 0x73, 0xd2,
	0xf5, 0x74, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x48, 0x35, 0x4a, 0x2e, 0xa9, 0x2c,
	0x48, 0x2d, 0x96, 0x12, 0x81, 0xa8, 0x4b, 0xcd, 0x73, 0x47, 0x92, 0x57, 0x8a, 0xe2, 0x92, 0x40,
	0xd6, 0x1f, 0x9f, 0x9a, 0x17, 0x9f, 0xee, 0xe7, 0x14, 0xef, 0xe9, 0x12, 0x5f, 0x22, 0x64, 0xc7,
	0xc5, 0x9b, 0x0e, 0x96, 0x83, 0x0a, 0x49, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x1b, 0x49, 0xe9, 0xc1,
	0xcc, 0xd4, 0x43, 0x32, 0x12, 0xac, 0x25, 0x88, 0x1b, 0xa2, 0xc1, 0xdd, 0xcf, 0xc9, 0xd3, 0x25,
	0x89, 0x0d, 0x6c, 0x85, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xb4, 0x08, 0x06, 0x96, 0xa2, 0x00,
	0x00, 0x00,
}
