// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ProtocolIE-Container.proto

package e2ctypes

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProtocolIE_Container_1544P0T struct {
	List                 []*RICsubscriptionRequest_IEsT `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *ProtocolIE_Container_1544P0T) Reset()         { *m = ProtocolIE_Container_1544P0T{} }
func (m *ProtocolIE_Container_1544P0T) String() string { return proto.CompactTextString(m) }
func (*ProtocolIE_Container_1544P0T) ProtoMessage()    {}
func (*ProtocolIE_Container_1544P0T) Descriptor() ([]byte, []int) {
	return fileDescriptor_86288059cc55b0eb, []int{0}
}

func (m *ProtocolIE_Container_1544P0T) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtocolIE_Container_1544P0T.Unmarshal(m, b)
}
func (m *ProtocolIE_Container_1544P0T) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtocolIE_Container_1544P0T.Marshal(b, m, deterministic)
}
func (m *ProtocolIE_Container_1544P0T) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtocolIE_Container_1544P0T.Merge(m, src)
}
func (m *ProtocolIE_Container_1544P0T) XXX_Size() int {
	return xxx_messageInfo_ProtocolIE_Container_1544P0T.Size(m)
}
func (m *ProtocolIE_Container_1544P0T) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtocolIE_Container_1544P0T.DiscardUnknown(m)
}

var xxx_messageInfo_ProtocolIE_Container_1544P0T proto.InternalMessageInfo

func (m *ProtocolIE_Container_1544P0T) GetList() []*RICsubscriptionRequest_IEsT {
	if m != nil {
		return m.List
	}
	return nil
}

type ProtocolIE_Container_1544P1T struct {
	List                 []*RICsubscriptionResponse_IEsT `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *ProtocolIE_Container_1544P1T) Reset()         { *m = ProtocolIE_Container_1544P1T{} }
func (m *ProtocolIE_Container_1544P1T) String() string { return proto.CompactTextString(m) }
func (*ProtocolIE_Container_1544P1T) ProtoMessage()    {}
func (*ProtocolIE_Container_1544P1T) Descriptor() ([]byte, []int) {
	return fileDescriptor_86288059cc55b0eb, []int{1}
}

func (m *ProtocolIE_Container_1544P1T) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtocolIE_Container_1544P1T.Unmarshal(m, b)
}
func (m *ProtocolIE_Container_1544P1T) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtocolIE_Container_1544P1T.Marshal(b, m, deterministic)
}
func (m *ProtocolIE_Container_1544P1T) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtocolIE_Container_1544P1T.Merge(m, src)
}
func (m *ProtocolIE_Container_1544P1T) XXX_Size() int {
	return xxx_messageInfo_ProtocolIE_Container_1544P1T.Size(m)
}
func (m *ProtocolIE_Container_1544P1T) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtocolIE_Container_1544P1T.DiscardUnknown(m)
}

var xxx_messageInfo_ProtocolIE_Container_1544P1T proto.InternalMessageInfo

func (m *ProtocolIE_Container_1544P1T) GetList() []*RICsubscriptionResponse_IEsT {
	if m != nil {
		return m.List
	}
	return nil
}

type ProtocolIE_Container_1544P2T struct {
	List                 []*RICsubscriptionFailure_IEsT `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *ProtocolIE_Container_1544P2T) Reset()         { *m = ProtocolIE_Container_1544P2T{} }
func (m *ProtocolIE_Container_1544P2T) String() string { return proto.CompactTextString(m) }
func (*ProtocolIE_Container_1544P2T) ProtoMessage()    {}
func (*ProtocolIE_Container_1544P2T) Descriptor() ([]byte, []int) {
	return fileDescriptor_86288059cc55b0eb, []int{2}
}

func (m *ProtocolIE_Container_1544P2T) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtocolIE_Container_1544P2T.Unmarshal(m, b)
}
func (m *ProtocolIE_Container_1544P2T) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtocolIE_Container_1544P2T.Marshal(b, m, deterministic)
}
func (m *ProtocolIE_Container_1544P2T) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtocolIE_Container_1544P2T.Merge(m, src)
}
func (m *ProtocolIE_Container_1544P2T) XXX_Size() int {
	return xxx_messageInfo_ProtocolIE_Container_1544P2T.Size(m)
}
func (m *ProtocolIE_Container_1544P2T) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtocolIE_Container_1544P2T.DiscardUnknown(m)
}

var xxx_messageInfo_ProtocolIE_Container_1544P2T proto.InternalMessageInfo

func (m *ProtocolIE_Container_1544P2T) GetList() []*RICsubscriptionFailure_IEsT {
	if m != nil {
		return m.List
	}
	return nil
}

type ProtocolIE_Container_1544P4T struct {
	List                 []*RICsubscriptionDeleteResponse_IEsT `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *ProtocolIE_Container_1544P4T) Reset()         { *m = ProtocolIE_Container_1544P4T{} }
func (m *ProtocolIE_Container_1544P4T) String() string { return proto.CompactTextString(m) }
func (*ProtocolIE_Container_1544P4T) ProtoMessage()    {}
func (*ProtocolIE_Container_1544P4T) Descriptor() ([]byte, []int) {
	return fileDescriptor_86288059cc55b0eb, []int{3}
}

func (m *ProtocolIE_Container_1544P4T) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtocolIE_Container_1544P4T.Unmarshal(m, b)
}
func (m *ProtocolIE_Container_1544P4T) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtocolIE_Container_1544P4T.Marshal(b, m, deterministic)
}
func (m *ProtocolIE_Container_1544P4T) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtocolIE_Container_1544P4T.Merge(m, src)
}
func (m *ProtocolIE_Container_1544P4T) XXX_Size() int {
	return xxx_messageInfo_ProtocolIE_Container_1544P4T.Size(m)
}
func (m *ProtocolIE_Container_1544P4T) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtocolIE_Container_1544P4T.DiscardUnknown(m)
}

var xxx_messageInfo_ProtocolIE_Container_1544P4T proto.InternalMessageInfo

func (m *ProtocolIE_Container_1544P4T) GetList() []*RICsubscriptionDeleteResponse_IEsT {
	if m != nil {
		return m.List
	}
	return nil
}

type ProtocolIE_Container_1544P5T struct {
	List                 []*RICsubscriptionDeleteFailure_IEsT `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *ProtocolIE_Container_1544P5T) Reset()         { *m = ProtocolIE_Container_1544P5T{} }
func (m *ProtocolIE_Container_1544P5T) String() string { return proto.CompactTextString(m) }
func (*ProtocolIE_Container_1544P5T) ProtoMessage()    {}
func (*ProtocolIE_Container_1544P5T) Descriptor() ([]byte, []int) {
	return fileDescriptor_86288059cc55b0eb, []int{4}
}

func (m *ProtocolIE_Container_1544P5T) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtocolIE_Container_1544P5T.Unmarshal(m, b)
}
func (m *ProtocolIE_Container_1544P5T) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtocolIE_Container_1544P5T.Marshal(b, m, deterministic)
}
func (m *ProtocolIE_Container_1544P5T) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtocolIE_Container_1544P5T.Merge(m, src)
}
func (m *ProtocolIE_Container_1544P5T) XXX_Size() int {
	return xxx_messageInfo_ProtocolIE_Container_1544P5T.Size(m)
}
func (m *ProtocolIE_Container_1544P5T) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtocolIE_Container_1544P5T.DiscardUnknown(m)
}

var xxx_messageInfo_ProtocolIE_Container_1544P5T proto.InternalMessageInfo

func (m *ProtocolIE_Container_1544P5T) GetList() []*RICsubscriptionDeleteFailure_IEsT {
	if m != nil {
		return m.List
	}
	return nil
}

type ProtocolIE_Container_1544P6T struct {
	List                 []*RICindication_IEsT `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ProtocolIE_Container_1544P6T) Reset()         { *m = ProtocolIE_Container_1544P6T{} }
func (m *ProtocolIE_Container_1544P6T) String() string { return proto.CompactTextString(m) }
func (*ProtocolIE_Container_1544P6T) ProtoMessage()    {}
func (*ProtocolIE_Container_1544P6T) Descriptor() ([]byte, []int) {
	return fileDescriptor_86288059cc55b0eb, []int{5}
}

func (m *ProtocolIE_Container_1544P6T) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtocolIE_Container_1544P6T.Unmarshal(m, b)
}
func (m *ProtocolIE_Container_1544P6T) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtocolIE_Container_1544P6T.Marshal(b, m, deterministic)
}
func (m *ProtocolIE_Container_1544P6T) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtocolIE_Container_1544P6T.Merge(m, src)
}
func (m *ProtocolIE_Container_1544P6T) XXX_Size() int {
	return xxx_messageInfo_ProtocolIE_Container_1544P6T.Size(m)
}
func (m *ProtocolIE_Container_1544P6T) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtocolIE_Container_1544P6T.DiscardUnknown(m)
}

var xxx_messageInfo_ProtocolIE_Container_1544P6T proto.InternalMessageInfo

func (m *ProtocolIE_Container_1544P6T) GetList() []*RICindication_IEsT {
	if m != nil {
		return m.List
	}
	return nil
}

type ProtocolIE_Container_1544P8T struct {
	List                 []*RICcontrolAcknowledge_IEsT `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *ProtocolIE_Container_1544P8T) Reset()         { *m = ProtocolIE_Container_1544P8T{} }
func (m *ProtocolIE_Container_1544P8T) String() string { return proto.CompactTextString(m) }
func (*ProtocolIE_Container_1544P8T) ProtoMessage()    {}
func (*ProtocolIE_Container_1544P8T) Descriptor() ([]byte, []int) {
	return fileDescriptor_86288059cc55b0eb, []int{6}
}

func (m *ProtocolIE_Container_1544P8T) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtocolIE_Container_1544P8T.Unmarshal(m, b)
}
func (m *ProtocolIE_Container_1544P8T) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtocolIE_Container_1544P8T.Marshal(b, m, deterministic)
}
func (m *ProtocolIE_Container_1544P8T) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtocolIE_Container_1544P8T.Merge(m, src)
}
func (m *ProtocolIE_Container_1544P8T) XXX_Size() int {
	return xxx_messageInfo_ProtocolIE_Container_1544P8T.Size(m)
}
func (m *ProtocolIE_Container_1544P8T) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtocolIE_Container_1544P8T.DiscardUnknown(m)
}

var xxx_messageInfo_ProtocolIE_Container_1544P8T proto.InternalMessageInfo

func (m *ProtocolIE_Container_1544P8T) GetList() []*RICcontrolAcknowledge_IEsT {
	if m != nil {
		return m.List
	}
	return nil
}

type ProtocolIE_Container_1544P9T struct {
	List                 []*RICcontrolFailure_IEsT `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ProtocolIE_Container_1544P9T) Reset()         { *m = ProtocolIE_Container_1544P9T{} }
func (m *ProtocolIE_Container_1544P9T) String() string { return proto.CompactTextString(m) }
func (*ProtocolIE_Container_1544P9T) ProtoMessage()    {}
func (*ProtocolIE_Container_1544P9T) Descriptor() ([]byte, []int) {
	return fileDescriptor_86288059cc55b0eb, []int{7}
}

func (m *ProtocolIE_Container_1544P9T) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtocolIE_Container_1544P9T.Unmarshal(m, b)
}
func (m *ProtocolIE_Container_1544P9T) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtocolIE_Container_1544P9T.Marshal(b, m, deterministic)
}
func (m *ProtocolIE_Container_1544P9T) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtocolIE_Container_1544P9T.Merge(m, src)
}
func (m *ProtocolIE_Container_1544P9T) XXX_Size() int {
	return xxx_messageInfo_ProtocolIE_Container_1544P9T.Size(m)
}
func (m *ProtocolIE_Container_1544P9T) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtocolIE_Container_1544P9T.DiscardUnknown(m)
}

var xxx_messageInfo_ProtocolIE_Container_1544P9T proto.InternalMessageInfo

func (m *ProtocolIE_Container_1544P9T) GetList() []*RICcontrolFailure_IEsT {
	if m != nil {
		return m.List
	}
	return nil
}

type ProtocolIE_Container_1544P10T struct {
	List                 []*ErrorIndication_IEsT `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ProtocolIE_Container_1544P10T) Reset()         { *m = ProtocolIE_Container_1544P10T{} }
func (m *ProtocolIE_Container_1544P10T) String() string { return proto.CompactTextString(m) }
func (*ProtocolIE_Container_1544P10T) ProtoMessage()    {}
func (*ProtocolIE_Container_1544P10T) Descriptor() ([]byte, []int) {
	return fileDescriptor_86288059cc55b0eb, []int{8}
}

func (m *ProtocolIE_Container_1544P10T) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtocolIE_Container_1544P10T.Unmarshal(m, b)
}
func (m *ProtocolIE_Container_1544P10T) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtocolIE_Container_1544P10T.Marshal(b, m, deterministic)
}
func (m *ProtocolIE_Container_1544P10T) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtocolIE_Container_1544P10T.Merge(m, src)
}
func (m *ProtocolIE_Container_1544P10T) XXX_Size() int {
	return xxx_messageInfo_ProtocolIE_Container_1544P10T.Size(m)
}
func (m *ProtocolIE_Container_1544P10T) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtocolIE_Container_1544P10T.DiscardUnknown(m)
}

var xxx_messageInfo_ProtocolIE_Container_1544P10T proto.InternalMessageInfo

func (m *ProtocolIE_Container_1544P10T) GetList() []*ErrorIndication_IEsT {
	if m != nil {
		return m.List
	}
	return nil
}

type ProtocolIE_Container_1544P11T struct {
	List                 []*E2SetupRequestIEsT `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ProtocolIE_Container_1544P11T) Reset()         { *m = ProtocolIE_Container_1544P11T{} }
func (m *ProtocolIE_Container_1544P11T) String() string { return proto.CompactTextString(m) }
func (*ProtocolIE_Container_1544P11T) ProtoMessage()    {}
func (*ProtocolIE_Container_1544P11T) Descriptor() ([]byte, []int) {
	return fileDescriptor_86288059cc55b0eb, []int{9}
}

func (m *ProtocolIE_Container_1544P11T) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtocolIE_Container_1544P11T.Unmarshal(m, b)
}
func (m *ProtocolIE_Container_1544P11T) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtocolIE_Container_1544P11T.Marshal(b, m, deterministic)
}
func (m *ProtocolIE_Container_1544P11T) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtocolIE_Container_1544P11T.Merge(m, src)
}
func (m *ProtocolIE_Container_1544P11T) XXX_Size() int {
	return xxx_messageInfo_ProtocolIE_Container_1544P11T.Size(m)
}
func (m *ProtocolIE_Container_1544P11T) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtocolIE_Container_1544P11T.DiscardUnknown(m)
}

var xxx_messageInfo_ProtocolIE_Container_1544P11T proto.InternalMessageInfo

func (m *ProtocolIE_Container_1544P11T) GetList() []*E2SetupRequestIEsT {
	if m != nil {
		return m.List
	}
	return nil
}

type ProtocolIE_Container_1544P12T struct {
	List                 []*E2SetupResponseIEsT `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ProtocolIE_Container_1544P12T) Reset()         { *m = ProtocolIE_Container_1544P12T{} }
func (m *ProtocolIE_Container_1544P12T) String() string { return proto.CompactTextString(m) }
func (*ProtocolIE_Container_1544P12T) ProtoMessage()    {}
func (*ProtocolIE_Container_1544P12T) Descriptor() ([]byte, []int) {
	return fileDescriptor_86288059cc55b0eb, []int{10}
}

func (m *ProtocolIE_Container_1544P12T) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtocolIE_Container_1544P12T.Unmarshal(m, b)
}
func (m *ProtocolIE_Container_1544P12T) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtocolIE_Container_1544P12T.Marshal(b, m, deterministic)
}
func (m *ProtocolIE_Container_1544P12T) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtocolIE_Container_1544P12T.Merge(m, src)
}
func (m *ProtocolIE_Container_1544P12T) XXX_Size() int {
	return xxx_messageInfo_ProtocolIE_Container_1544P12T.Size(m)
}
func (m *ProtocolIE_Container_1544P12T) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtocolIE_Container_1544P12T.DiscardUnknown(m)
}

var xxx_messageInfo_ProtocolIE_Container_1544P12T proto.InternalMessageInfo

func (m *ProtocolIE_Container_1544P12T) GetList() []*E2SetupResponseIEsT {
	if m != nil {
		return m.List
	}
	return nil
}

type ProtocolIE_Container_1544P13T struct {
	List                 []*E2SetupFailureIEsT `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ProtocolIE_Container_1544P13T) Reset()         { *m = ProtocolIE_Container_1544P13T{} }
func (m *ProtocolIE_Container_1544P13T) String() string { return proto.CompactTextString(m) }
func (*ProtocolIE_Container_1544P13T) ProtoMessage()    {}
func (*ProtocolIE_Container_1544P13T) Descriptor() ([]byte, []int) {
	return fileDescriptor_86288059cc55b0eb, []int{11}
}

func (m *ProtocolIE_Container_1544P13T) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtocolIE_Container_1544P13T.Unmarshal(m, b)
}
func (m *ProtocolIE_Container_1544P13T) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtocolIE_Container_1544P13T.Marshal(b, m, deterministic)
}
func (m *ProtocolIE_Container_1544P13T) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtocolIE_Container_1544P13T.Merge(m, src)
}
func (m *ProtocolIE_Container_1544P13T) XXX_Size() int {
	return xxx_messageInfo_ProtocolIE_Container_1544P13T.Size(m)
}
func (m *ProtocolIE_Container_1544P13T) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtocolIE_Container_1544P13T.DiscardUnknown(m)
}

var xxx_messageInfo_ProtocolIE_Container_1544P13T proto.InternalMessageInfo

func (m *ProtocolIE_Container_1544P13T) GetList() []*E2SetupFailureIEsT {
	if m != nil {
		return m.List
	}
	return nil
}

type ProtocolIE_Container_1544P15T struct {
	List                 []*ResetResponseIEsT `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ProtocolIE_Container_1544P15T) Reset()         { *m = ProtocolIE_Container_1544P15T{} }
func (m *ProtocolIE_Container_1544P15T) String() string { return proto.CompactTextString(m) }
func (*ProtocolIE_Container_1544P15T) ProtoMessage()    {}
func (*ProtocolIE_Container_1544P15T) Descriptor() ([]byte, []int) {
	return fileDescriptor_86288059cc55b0eb, []int{12}
}

func (m *ProtocolIE_Container_1544P15T) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtocolIE_Container_1544P15T.Unmarshal(m, b)
}
func (m *ProtocolIE_Container_1544P15T) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtocolIE_Container_1544P15T.Marshal(b, m, deterministic)
}
func (m *ProtocolIE_Container_1544P15T) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtocolIE_Container_1544P15T.Merge(m, src)
}
func (m *ProtocolIE_Container_1544P15T) XXX_Size() int {
	return xxx_messageInfo_ProtocolIE_Container_1544P15T.Size(m)
}
func (m *ProtocolIE_Container_1544P15T) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtocolIE_Container_1544P15T.DiscardUnknown(m)
}

var xxx_messageInfo_ProtocolIE_Container_1544P15T proto.InternalMessageInfo

func (m *ProtocolIE_Container_1544P15T) GetList() []*ResetResponseIEsT {
	if m != nil {
		return m.List
	}
	return nil
}

type ProtocolIE_Container_1544P17T struct {
	List                 []*RICserviceUpdateAcknowledge_IEsT `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *ProtocolIE_Container_1544P17T) Reset()         { *m = ProtocolIE_Container_1544P17T{} }
func (m *ProtocolIE_Container_1544P17T) String() string { return proto.CompactTextString(m) }
func (*ProtocolIE_Container_1544P17T) ProtoMessage()    {}
func (*ProtocolIE_Container_1544P17T) Descriptor() ([]byte, []int) {
	return fileDescriptor_86288059cc55b0eb, []int{13}
}

func (m *ProtocolIE_Container_1544P17T) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtocolIE_Container_1544P17T.Unmarshal(m, b)
}
func (m *ProtocolIE_Container_1544P17T) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtocolIE_Container_1544P17T.Marshal(b, m, deterministic)
}
func (m *ProtocolIE_Container_1544P17T) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtocolIE_Container_1544P17T.Merge(m, src)
}
func (m *ProtocolIE_Container_1544P17T) XXX_Size() int {
	return xxx_messageInfo_ProtocolIE_Container_1544P17T.Size(m)
}
func (m *ProtocolIE_Container_1544P17T) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtocolIE_Container_1544P17T.DiscardUnknown(m)
}

var xxx_messageInfo_ProtocolIE_Container_1544P17T proto.InternalMessageInfo

func (m *ProtocolIE_Container_1544P17T) GetList() []*RICserviceUpdateAcknowledge_IEsT {
	if m != nil {
		return m.List
	}
	return nil
}

type ProtocolIE_Container_1544P18T struct {
	List                 []*RICserviceUpdateFailure_IEsT `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *ProtocolIE_Container_1544P18T) Reset()         { *m = ProtocolIE_Container_1544P18T{} }
func (m *ProtocolIE_Container_1544P18T) String() string { return proto.CompactTextString(m) }
func (*ProtocolIE_Container_1544P18T) ProtoMessage()    {}
func (*ProtocolIE_Container_1544P18T) Descriptor() ([]byte, []int) {
	return fileDescriptor_86288059cc55b0eb, []int{14}
}

func (m *ProtocolIE_Container_1544P18T) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtocolIE_Container_1544P18T.Unmarshal(m, b)
}
func (m *ProtocolIE_Container_1544P18T) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtocolIE_Container_1544P18T.Marshal(b, m, deterministic)
}
func (m *ProtocolIE_Container_1544P18T) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtocolIE_Container_1544P18T.Merge(m, src)
}
func (m *ProtocolIE_Container_1544P18T) XXX_Size() int {
	return xxx_messageInfo_ProtocolIE_Container_1544P18T.Size(m)
}
func (m *ProtocolIE_Container_1544P18T) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtocolIE_Container_1544P18T.DiscardUnknown(m)
}

var xxx_messageInfo_ProtocolIE_Container_1544P18T proto.InternalMessageInfo

func (m *ProtocolIE_Container_1544P18T) GetList() []*RICserviceUpdateFailure_IEsT {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*ProtocolIE_Container_1544P0T)(nil), "e2ctypes.ProtocolIE_Container_1544P0_t")
	proto.RegisterType((*ProtocolIE_Container_1544P1T)(nil), "e2ctypes.ProtocolIE_Container_1544P1_t")
	proto.RegisterType((*ProtocolIE_Container_1544P2T)(nil), "e2ctypes.ProtocolIE_Container_1544P2_t")
	proto.RegisterType((*ProtocolIE_Container_1544P4T)(nil), "e2ctypes.ProtocolIE_Container_1544P4_t")
	proto.RegisterType((*ProtocolIE_Container_1544P5T)(nil), "e2ctypes.ProtocolIE_Container_1544P5_t")
	proto.RegisterType((*ProtocolIE_Container_1544P6T)(nil), "e2ctypes.ProtocolIE_Container_1544P6_t")
	proto.RegisterType((*ProtocolIE_Container_1544P8T)(nil), "e2ctypes.ProtocolIE_Container_1544P8_t")
	proto.RegisterType((*ProtocolIE_Container_1544P9T)(nil), "e2ctypes.ProtocolIE_Container_1544P9_t")
	proto.RegisterType((*ProtocolIE_Container_1544P10T)(nil), "e2ctypes.ProtocolIE_Container_1544P10_t")
	proto.RegisterType((*ProtocolIE_Container_1544P11T)(nil), "e2ctypes.ProtocolIE_Container_1544P11_t")
	proto.RegisterType((*ProtocolIE_Container_1544P12T)(nil), "e2ctypes.ProtocolIE_Container_1544P12_t")
	proto.RegisterType((*ProtocolIE_Container_1544P13T)(nil), "e2ctypes.ProtocolIE_Container_1544P13_t")
	proto.RegisterType((*ProtocolIE_Container_1544P15T)(nil), "e2ctypes.ProtocolIE_Container_1544P15_t")
	proto.RegisterType((*ProtocolIE_Container_1544P17T)(nil), "e2ctypes.ProtocolIE_Container_1544P17_t")
	proto.RegisterType((*ProtocolIE_Container_1544P18T)(nil), "e2ctypes.ProtocolIE_Container_1544P18_t")
}

func init() { proto.RegisterFile("ProtocolIE-Container.proto", fileDescriptor_86288059cc55b0eb) }

var fileDescriptor_86288059cc55b0eb = []byte{
	// 397 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0xd4, 0xcf, 0x6b, 0xe2, 0x40,
	0x14, 0x07, 0x70, 0x96, 0x5d, 0x96, 0x25, 0x7b, 0x9b, 0xc3, 0xb2, 0xc8, 0xea, 0xee, 0x0a, 0xfb,
	0x03, 0x5a, 0xc5, 0x44, 0x6d, 0xb5, 0x3d, 0xb4, 0x62, 0x23, 0xe4, 0x26, 0x69, 0xed, 0xa1, 0x3f,
	0x18, 0x62, 0xf2, 0x28, 0x43, 0x43, 0x26, 0x9d, 0x79, 0x69, 0xe9, 0x7f, 0x5f, 0xa2, 0xb6, 0xe6,
	0xc1, 0x38, 0xda, 0xab, 0x26, 0x9f, 0xef, 0xcb, 0xcb, 0x37, 0xe3, 0xd4, 0xa6, 0x4a, 0xa2, 0x8c,
	0x65, 0x1a, 0xf8, 0xad, 0xb1, 0xcc, 0x30, 0x12, 0x19, 0xa8, 0x76, 0x5e, 0xfe, 0xc8, 0xbe, 0x80,
	0x17, 0xe3, 0x73, 0x0e, 0xba, 0xf6, 0xad, 0x72, 0xd5, 0x44, 0x40, 0x9a, 0x2c, 0xaf, 0x68, 0x5e,
	0x3b, 0xf5, 0xf5, 0x3f, 0xfc, 0xed, 0x7e, 0xee, 0xf6, 0x7b, 0xbd, 0x69, 0x87, 0x23, 0x3b, 0x72,
	0x3e, 0xa5, 0x42, 0xe3, 0xf7, 0x0f, 0xbf, 0x3e, 0xfe, 0xff, 0xea, 0xfd, 0x6d, 0xbf, 0x8a, 0xed,
	0x30, 0x18, 0xeb, 0x62, 0xae, 0x63, 0x25, 0x72, 0x14, 0x32, 0x0b, 0xe1, 0xa1, 0x00, 0x8d, 0x3c,
	0xf0, 0x35, 0xc7, 0x70, 0x71, 0x4f, 0xf3, 0xc6, 0x86, 0xbb, 0x1c, 0xd9, 0x31, 0xc1, 0xff, 0x59,
	0x70, 0x9d, 0xcb, 0x4c, 0x03, 0xd1, 0xad, 0xa3, 0x7b, 0xef, 0x18, 0x7d, 0x12, 0x89, 0xb4, 0x50,
	0x14, 0x9f, 0xdb, 0xf0, 0x1e, 0x47, 0x36, 0x22, 0x78, 0x6b, 0x23, 0x7e, 0x06, 0x29, 0x20, 0x18,
	0x1f, 0x20, 0xb2, 0x65, 0xf4, 0x39, 0xb2, 0x53, 0x92, 0xb1, 0xbf, 0x25, 0xc3, 0xf4, 0x18, 0xa1,
	0x2d, 0xe2, 0x80, 0x23, 0x73, 0x49, 0x44, 0x9d, 0x44, 0x88, 0x2c, 0x11, 0x71, 0x54, 0x06, 0x10,
	0xf3, 0xca, 0x66, 0x0e, 0x38, 0xb2, 0x21, 0x31, 0xff, 0x10, 0x33, 0x96, 0x19, 0x2a, 0x99, 0x8e,
	0xe2, 0xfb, 0x4c, 0x3e, 0xa5, 0x90, 0xdc, 0xd1, 0x79, 0x2f, 0x6d, 0xf6, 0x90, 0x23, 0xeb, 0x13,
	0xfb, 0xb7, 0xc9, 0x36, 0xed, 0x61, 0xe6, 0x34, 0x2c, 0x4d, 0x2c, 0x7b, 0xde, 0x25, 0xf0, 0xcf,
	0x35, 0xec, 0x2b, 0x25, 0x55, 0x60, 0x5e, 0xc5, 0xb9, 0x95, 0x75, 0x6d, 0xfb, 0xf5, 0x3d, 0x0d,
	0x58, 0xe4, 0xab, 0xcf, 0xa6, 0x8a, 0x5e, 0x58, 0xd1, 0xb2, 0xd8, 0x1e, 0x41, 0x1b, 0x06, 0x74,
	0xd9, 0xb6, 0xdd, 0x47, 0xed, 0xee, 0x30, 0xea, 0x6a, 0xaf, 0xb4, 0x5e, 0x36, 0xb4, 0xac, 0x70,
	0x87, 0xa0, 0x3f, 0x2a, 0xef, 0x0b, 0x34, 0xa0, 0x69, 0xd0, 0xc8, 0x6a, 0x1e, 0x72, 0x64, 0x27,
	0xc4, 0xdc, 0xa3, 0x9f, 0x05, 0xa8, 0x47, 0x11, 0xc3, 0x2c, 0x4f, 0x22, 0x84, 0x4d, 0x2d, 0xbb,
	0xb5, 0x46, 0x0c, 0xb6, 0x1d, 0x4c, 0xd5, 0x08, 0x43, 0xd9, 0xe6, 0x9f, 0x17, 0x47, 0x6b, 0xf7,
	0x25, 0x00, 0x00, 0xff, 0xff, 0x3e, 0x14, 0xfc, 0x50, 0x9a, 0x05, 0x00, 0x00,
}
