// Code generated by protoc-gen-go. DO NOT EDIT.
// RICindicationType.proto is a deprecated file.

package e2ctypes

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RICindicationType int32 // Deprecated: Do not use.
const (
	RICindicationType_RICindicationType_report RICindicationType = 0 // Deprecated: Do not use.
	RICindicationType_RICindicationType_insert RICindicationType = 1 // Deprecated: Do not use.
)

var RICindicationType_name = map[int32]string{
	0: "RICindicationType_report",
	1: "RICindicationType_insert",
}

var RICindicationType_value = map[string]int32{
	"RICindicationType_report": 0,
	"RICindicationType_insert": 1,
}

func (x RICindicationType) String() string {
	return proto.EnumName(RICindicationType_name, int32(x))
}

func (RICindicationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c96e47daccf968c5, []int{0}
}

func init() {
	proto.RegisterEnum("e2ctypes.RICindicationType", RICindicationType_name, RICindicationType_value)
}

func init() { proto.RegisterFile("RICindicationType.proto", fileDescriptor_c96e47daccf968c5) }

var fileDescriptor_c96e47daccf968c5 = []byte{
	// 111 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x0f, 0xf2, 0x74, 0xce,
	0xcc, 0x4b, 0xc9, 0x4c, 0x4e, 0x2c, 0xc9, 0xcc, 0xcf, 0x0b, 0xa9, 0x2c, 0x48, 0xd5, 0x2b, 0x28,
	0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x48, 0x35, 0x4a, 0x2e, 0xa9, 0x2c, 0x48, 0x2d, 0xd6, 0x8a, 0xe6,
	0x12, 0xc4, 0x50, 0x24, 0xa4, 0xc0, 0x25, 0x81, 0x21, 0x18, 0x5f, 0x94, 0x5a, 0x90, 0x5f, 0x54,
	0x22, 0xc0, 0x20, 0xc5, 0xc4, 0xc1, 0x88, 0x5d, 0x45, 0x66, 0x5e, 0x71, 0x6a, 0x51, 0x89, 0x00,
	0x23, 0x48, 0x85, 0x14, 0x93, 0x04, 0xa3, 0x13, 0xf3, 0x0e, 0x46, 0xc6, 0x24, 0x36, 0xb0, 0x95,
	0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb7, 0xa9, 0xad, 0x75, 0x8d, 0x00, 0x00, 0x00,
}
